# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-08 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('archivo', models.FileField(upload_to='')),
                ('tipo', models.CharField(choices=[('Administrador', 'Administrador'), ('CEO', 'CEO'), ('SI', 'Superintendente'), ('Ejecutora', 'Ejecutora'), ('Escuela', 'Escuela'), ('Laboratorio', 'Laboratorio'), ('INIFED', 'INIFED'), ('Coor_Estatal', 'Coordinador Estatal de INIFED'), ('RTINIFED', 'Residente Técnico de INIFED'), ('IMTA', 'IMTA'), ('ECA', 'Encargado de Calidad de Agua'), ('EMB', 'Encargado de Mueble Bebedero')], max_length=20)),
            ],
        ),
    ]
