# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-14 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantilla',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
