# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-14 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0002_auto_20171014_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantilla',
            old_name='tipo',
            new_name='tipo_usuario',
        ),
        migrations.AddField(
            model_name='plantilla',
            name='fase',
            field=models.CharField(choices=[('Primer prueba de calidad de agua', 'Primer prueba de calidad de agua'), ('Inicio de trabajo', 'Inicio de trabajo'), ('Visita de acuerdos', 'Visita de acuerdos'), ('Construcción e instalación de Sistema bebedero', 'Construcción e instalación de Sistema bebedero'), ('Segunda prueba de calidad de agua', 'Segunda prueba de calidad de agua'), ('Inicio de funcionamiento', 'Inicio de funcionamiento'), ('Mantenimiento', 'Mantenimiento')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
