# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-18 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0005_auto_20171014_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantilla',
            name='tipo_usuario',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('CEO', 'CEO'), ('SI', 'Superintendente'), ('Ejecutora', 'Ejecutora'), ('Escuela', 'Escuela'), ('Laboratorio', 'Laboratorio'), ('INIFED', 'INIFED'), ('CEstatal', 'Coordinador Estatal de INIFED'), ('RTINIFED', 'Residente Técnico de INIFED'), ('IMTA', 'IMTA'), ('PQ', 'Procesos Químicos (Calidad de Agua)'), ('PM', 'Planta y Manufactura')], max_length=20),
        ),
    ]
