# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-08 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0008_auto_20171030_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantilla',
            name='tipo_usuario',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Ejecutora', 'Ejecutora'), ('Escuela', 'Escuela'), ('Laboratorio', 'Laboratorio'), ('INIFED', 'INIFED'), ('IMTA', 'IMTA'), ('PQ', 'Procesos Químicos (Calidad de Agua)'), ('PM', 'Planta y Manufactura')], max_length=20),
        ),
    ]
