# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-01 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0009_auto_20171108_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantilla',
            name='fase',
            field=models.CharField(choices=[('Pruebas de calidad de agua', 'Pruebas de calidad de agua'), ('Visita de acuerdos', 'Visita de acuerdos'), ('Inicio de trabajo', 'Inicio de trabajo'), ('Construcción e instalación de Sistema bebedero', 'Construcción e instalación de Sistema bebedero'), ('Inicio de funcionamiento', 'Inicio de funcionamiento'), ('Mantenimiento', 'Mantenimiento')], max_length=100),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='tipo_usuario',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Ejecutora', 'Ejecutora'), ('Escuela', 'Escuela'), ('Laboratorio', 'Laboratorio'), ('INIFED', 'INIFED'), ('PQ', 'Procesos Químicos (Calidad de Agua)'), ('PM', 'Planta y Manufactura')], max_length=20),
        ),
    ]
