# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 20:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bebederos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Pre-instalación', (('Convenio de ubicación', 'Convenio de ubicación'), ('Primer análisis de la calidad del agua', 'Primer análisis de la calidad del agua'))), ('Instalación', (('Llegada de material', 'Llegada de material'),)), ('Revisiones', (('Primera revisión mensual', 'Primera revisión mensual'), ('Segunda revisión mensual', 'Segunda revisión mensual'), ('Tercera revisión mensual', 'Tercera revisión mensual'), ('Cuarta revisión mensual', 'Cuarta revisión mensual'), ('Quinta revisión mensual', 'Quinta revisión mensual'), ('Sexta revisión mensual', 'Sexta revisión mensual')))], max_length=50)),
                ('archivo', models.FileField(upload_to='expedientes/archivos/%Y/%m/%d/')),
                ('foto', models.FileField(upload_to='expedientes/fotos/%Y/%m/%d/')),
                ('video', models.FileField(upload_to='expedientes/videos/%Y/%m/%d/')),
                ('creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('aprobado', models.BooleanField(default=False)),
                ('sistemabebedero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bebederos.SistemaBebedero')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('archivo', models.FileField(upload_to='plantillas/%Y/%m/%d/')),
                ('creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
