# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('evidencias', '0004_auto_20170614_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evidencia',
            options={'ordering': ['sistemabebedero', 'creacion']},
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
    ]
