# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('evidencias', '0005_auto_20170615_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencia',
            name='creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='foto',
            field=models.FileField(upload_to='expedientes/fotos/%Y/%m/%d/', verbose_name='Evidencia fotografia'),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='video',
            field=models.FileField(upload_to='expedientes/videos/%Y/%m/%d/', verbose_name='Evidencia audiovisual'),
        ),
    ]
