# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencias', '0006_auto_20170615_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencia',
            name='nombre',
            field=models.CharField(choices=[('Pre-instalación', (('Dictamen de ubicación', 'Dictamen de ubicación'), ('Constancia de toma de agua municipal', 'Constancia de toma de agua municipal'), ('Constancia de llegada de agua al laboratorio', 'Constancia de llegada de agua al laboratorio'), ('Resultados del primer análisis de la calidad del agua', 'Resultados del primer análisis de la calidad del agua'), ('Validación de la calidad del agua', 'Validación de la calidad del agua'))), ('Instalación', (('Constancia de llegada de material', 'Constancia de llegada de material'), ('Constancia de realización de la etapa: Limpieza, trazo y nivelación', 'Constancia de realización de la etapa: Limpieza, trazo y nivelación'), ('Constancia de realización de la etapa: Demoliciones y desmontajes', 'Constancia de realización de la etapa: Demoliciones y desmontajes'), ('Constancia de realización de la etapa: Excavaciones', 'Constancia de realización de la etapa: Excavaciones'), ('Constancia de realización de la etapa: Acero en refuerzo estructural', 'Constancia de realización de la etapa: Acero en refuerzo estructural'), ('Constancia de realización de la etapa: Albañileria y acabados', 'Constancia de realización de la etapa: Albañileria y acabados'), ('Constancia de realización de la etapa: Herreria y cubierta', 'Constancia de realización de la etapa: Herreria y cubierta'), ('Constancia de realización de la etapa: Instalación hidraulica', 'Constancia de realización de la etapa: Instalación hidraulica'), ('Constancia de realización de la etapa: Instalación sanitaria', 'Constancia de realización de la etapa: Instalación sanitaria'), ('Constancia de realización de la etapa: Instalación electrica', 'Constancia de realización de la etapa: Instalación electrica'), ('Constancia de realización de la etapa: Demoliciones y desmontajes', 'Constancia de realización de la etapa: Demoliciones y desmontajes'), ('Constancia de realización de la etapa: Obra exterior', 'Constancia de realización de la etapa: Obra exterior'), ('Constancia de realización de la etapa: bebedero', 'Constancia de realización de la etapa: Bebedero'))), ('Post-Instalación', (('Constancia de la llegada de la segunda muestra de agua al laboratorio', 'Constancia de la llegada de la segunda muestra de agua al laboratorio'), ('Resultados del segundo análisis de la calidad del agua', 'Resultados del segundo análisis de la calidad del agua'), ('Resultados del segundo análisis de la calidad del agua', 'Resultados del segundo análisis de la calidad del agua'), ('Dictamen del sistema avalado', 'Dictamen del sistema avalado'), ('Recibo de entrega de llaves', 'Recibo de entrega de llaves'), ('Acta de inicio de funcionamiento', 'Acta de inicio de funcionamiento'))), ('Revisiones', (('Revisión mensual (1er mes)', 'Revisión mensual (1er mes)'), ('Revisión mensual (2do mes)', 'Revisión mensual (2do mes)'), ('Revisión mensual (3er mes)', 'Revisión mensual (3er mes)'), ('Revisión mensual (4to mes)', 'Revisión mensual (4to mes)'), ('Revisión mensual (5to mes)', 'Revisión mensual (5to mes)'), ('Constancia de lavado y desinfeccion de tinaco y cisterna (6to mes)', 'Constancia de lavado y desinfeccion de tinaco y cisterna (6to mes)'), ('Revisión mensual (7mo mes)', 'Revisión mensual (7mo mes)'), ('Constancia de prueba periodica (8mo mes)', 'Constancia de prueba periodica (8mo mes)')))], max_length=100),
        ),
    ]
