# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencias', '0012_auto_20170717_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenciaprevia',
            name='aprobacion_imta',
            field=models.BooleanField(default=False),
        ),
    ]
