# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencias', '0013_evidenciaprevia_aprobacion_imta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenciaprevia',
            name='aprobacion_imta',
            field=models.CharField(blank=True, choices=[('Aprobado', 'Aprobado'), ('No aprobado', 'No aprobado')], max_length=20, null=True),
        ),
    ]
