# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencias', '0015_evidenciainstalacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenciainstalacion',
            name='nombre',
            field=models.CharField(choices=[('Constancia de llegada de naterial', 'Constancia de llegada de naterial'), ('Constancia de realización de la fase: Trabajos preliminares', 'Constancia de realización de la fase: Trabajos preliminares'), ('Constancia de realización de la fase: Albañileria', 'Constancia de realización de la fase: Albañileria'), ('Constancia de realización de la fase: Herreria', 'Constancia de realización de la fase: Herreria'), ('Constancia de realización de la fase: Instalaciones', 'Constancia de realización de la fase: Instalaciones'), ('Constancia de realización de la fase: Bebedero', 'Constancia de realización de la fase: Bebedero')], max_length=100),
        ),
    ]
