# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 17:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0009_sistemabebedero_identificador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evidencias', '0016_auto_20170718_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaPostInstalacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Constancia de segunda toma de agua', 'Constancia de segunda toma de agua'), ('Constancia de llegada de agua al laboratorio', 'Constancia de llegada de agua al laboratorio'), ('Resultados del segundo análisis de la calidad del agua', 'Resultados del segundo análisis de la calidad del agua'), ('Dictamen de sistema bebedero avalado', 'Dictamen de sistema bebedero avalado'), ('Acta de inicio de funcionamiento', 'Acta de inicio de funcionamiento')], max_length=100)),
                ('archivo', models.FileField(upload_to='expedientes/archivos/%Y/%m/%d/', verbose_name='Documento (solo pdf)')),
                ('foto', models.FileField(upload_to='expedientes/fotos/%Y/%m/%d/', verbose_name='Fotografía (Con camara de 5 megapixeles en adelante)')),
                ('video', models.FileField(upload_to='expedientes/videos/%Y/%m/%d/', verbose_name='Video (Con camara de 5 megapixeles en adelante)')),
                ('creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
                ('aprobado', models.BooleanField(default=False)),
                ('sistemabebedero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bebederos.SistemaBebedero')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sistemabebedero', 'creacion'],
            },
        ),
        migrations.AlterField(
            model_name='evidenciaprevia',
            name='nombre',
            field=models.CharField(choices=[('Dictamen de ubicación', 'Dictamen de ubicación'), ('Constancia de primera toma de agua', 'Constancia de primera toma de agua'), ('Constancia de llegada de agua al laboratorio', 'Constancia de llegada de agua al laboratorio'), ('Resultados del primer análisis de la calidad del agua', 'Resultados del primer análisis de la calidad del agua'), ('Validación de la calidad del agua', 'Validación de la calidad del agua')], max_length=100),
        ),
    ]
