# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 14:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimerVisita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constancia_de_visita', models.FileField(upload_to='visitas/1/constancia/%Y/%m/%d/')),
                ('hoja_de_cotizacion', models.FileField(upload_to='visitas/1/cotizacion/%Y/%m/%d/')),
                ('plantilla_fotografica', models.FileField(upload_to='visitas/1/plantilla/%Y/%m/%d/')),
                ('membrete_para_mail', models.FileField(upload_to='visitas/1/membrete/%Y/%m/%d/')),
                ('agenda', models.FileField(upload_to='visitas/1/agenda/%Y/%m/%d/')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['escuela'],
            },
        ),
    ]
