# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0003_primervisita_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='segundavisita',
            name='creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
    ]
