# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 15:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitas', '0004_segundavisita_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segundavisita',
            name='escuela',
        ),
        migrations.AddField(
            model_name='primervisita',
            name='sim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simaaa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='primervisita',
            name='escuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escuelaaaaa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SegundaVisita',
        ),
    ]
