# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 16:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitas', '0006_auto_20170727_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegundaVisita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acta_acuerdos', models.FileField(upload_to='visitas/2/acta/%Y/%m/%d/', verbose_name='Acta de acuerdos y ubicación del módulo')),
                ('reporte_de_toma', models.FileField(upload_to='visitas/2/reporte_de_toma/%Y/%m/%d/', verbose_name='Reporte de toma de muestra')),
                ('creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('escuela', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_segunda_visita', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['escuela'],
            },
        ),
        migrations.AlterField(
            model_name='primervisita',
            name='sim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sim_primera_visita', to=settings.AUTH_USER_MODEL),
        ),
    ]
