# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0007_auto_20170727_1112'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrimerVisita',
            new_name='VisitaAlSitio',
        ),
        migrations.RenameModel(
            old_name='SegundaVisita',
            new_name='VisitaDeAcuerdos',
        ),
        migrations.AlterModelOptions(
            name='visitaalsitio',
            options={'ordering': ['escuela'], 'verbose_name_plural': 'Primeras visitas'},
        ),
        migrations.AlterModelOptions(
            name='visitadeacuerdos',
            options={'ordering': ['escuela'], 'verbose_name_plural': 'Segundas visitas'},
        ),
    ]
