# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0008_auto_20170728_0918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitaalsitio',
            options={'ordering': ['escuela'], 'verbose_name_plural': 'Visitas al sitio'},
        ),
        migrations.AlterModelOptions(
            name='visitadeacuerdos',
            options={'ordering': ['escuela'], 'verbose_name_plural': 'visitas de acuerdos'},
        ),
    ]
