# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 20:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitas', '0009_auto_20170728_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaDeBebedero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acta_de_entrega', models.FileField(upload_to='visitas/3/acta/%Y/%m/%d/', verbose_name='Acta de entrega de trabajos')),
                ('convenio_de_responsabilidades', models.FileField(upload_to='visitas/3/responsabilidades/%Y/%m/%d/', verbose_name='Convenio de asignación de responsabilidades')),
                ('constancia_entrega_llaves', models.FileField(upload_to='visitas/3/responsabilidades/%Y/%m/%d/', verbose_name='Constancia de entrega de llaves')),
                ('video', models.FileField(upload_to='visitas/3/video/%Y/%m/%d/', verbose_name='Video de entrega de trabajos oficial al plantel y su correcto funcionamiento')),
                ('creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('escuela', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_entrega_bebedero', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'visitas de acuerdos',
                'ordering': ['escuela'],
            },
        ),
    ]
