# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0010_entregadebebedero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entregadebebedero',
            old_name='acta_de_entrega',
            new_name='acta_entrega',
        ),
        migrations.RenameField(
            model_name='entregadebebedero',
            old_name='convenio_de_responsabilidades',
            new_name='convenio_responsabilidades',
        ),
        migrations.RenameField(
            model_name='visitaalsitio',
            old_name='constancia_de_visita',
            new_name='constancia_visita',
        ),
        migrations.RenameField(
            model_name='visitaalsitio',
            old_name='hoja_de_cotizacion',
            new_name='hoja_cotizacion',
        ),
        migrations.RenameField(
            model_name='visitaalsitio',
            old_name='membrete_para_mail',
            new_name='membrete_mail',
        ),
        migrations.RenameField(
            model_name='visitadeacuerdos',
            old_name='reporte_de_toma',
            new_name='reporte_toma_agua',
        ),
        migrations.AlterField(
            model_name='entregadebebedero',
            name='constancia_entrega_llaves',
            field=models.FileField(upload_to='visitas/3/llaves/%Y/%m/%d/', verbose_name='Constancia de entrega de llaves'),
        ),
    ]
