# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0011_auto_20170728_1547'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VisitaDeAcuerdos',
            new_name='VisitaDeAcuerdo',
        ),
    ]
