# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0012_auto_20170729_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entregadebebedero',
            options={'ordering': ['escuela'], 'verbose_name_plural': 'Entrega de bebederos'},
        ),
    ]
