# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-10 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0013_auto_20170729_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitaalsitio',
            name='hoja_cotizacion',
            field=models.FileField(upload_to='visitas/1/cotizacion/%Y/%m/%d/', verbose_name='Hoja de cotización'),
        ),
        migrations.AlterField(
            model_name='visitaalsitio',
            name='plantilla_fotografica',
            field=models.FileField(upload_to='visitas/1/plantilla/%Y/%m/%d/', verbose_name='Plantilla fotográfica'),
        ),
    ]
