# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0014_auto_20170810_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitaalsitio',
            name='agenda',
        ),
        migrations.RemoveField(
            model_name='visitaalsitio',
            name='constancia_visita',
        ),
        migrations.RemoveField(
            model_name='visitaalsitio',
            name='hoja_cotizacion',
        ),
        migrations.RemoveField(
            model_name='visitaalsitio',
            name='membrete_mail',
        ),
        migrations.RemoveField(
            model_name='visitaalsitio',
            name='plantilla_fotografica',
        ),
        migrations.AddField(
            model_name='visitaalsitio',
            name='acta_visita',
            field=models.FileField(blank=True, null=True, upload_to='visitas/1/acta/%Y/%m/%d/', verbose_name='Acta de visita'),
        ),
        migrations.AddField(
            model_name='visitaalsitio',
            name='copia_INE',
            field=models.FileField(blank=True, null=True, upload_to='visitas/1/INE/%Y/%m/%d/', verbose_name='Copia de INE'),
        ),
        migrations.AddField(
            model_name='visitadeacuerdo',
            name='cedula_identificacion',
            field=models.FileField(blank=True, null=True, upload_to='visitas/2/cedula/%Y/%m/%d/', verbose_name='Cédula de identificación basica'),
        ),
        migrations.AddField(
            model_name='visitadeacuerdo',
            name='constancia_integracion_comite',
            field=models.FileField(blank=True, null=True, upload_to='visitas/2/cedula/%Y/%m/%d/', verbose_name='Constancia de Integración de Comité'),
        ),
        migrations.AddField(
            model_name='visitadeacuerdo',
            name='convenio_concertacion',
            field=models.FileField(blank=True, null=True, upload_to='visitas/2/concertacion/%Y/%m/%d/', verbose_name='Convenio de concertación de aplicación de recurso'),
        ),
    ]
