# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-29 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0015_auto_20170811_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entregadebebedero',
            options={'ordering': ['escuela'], 'verbose_name_plural': 'Entregas de bebedero'},
        ),
        migrations.AlterModelOptions(
            name='visitadeacuerdo',
            options={'ordering': ['escuela'], 'verbose_name_plural': 'Visitas de acuerdo'},
        ),
        migrations.RemoveField(
            model_name='visitadeacuerdo',
            name='reporte_toma_agua',
        ),
    ]
