# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0015_auto_20170811_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitadeacuerdo',
            name='reporte_toma_agua',
        ),
    ]
