# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-01 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0016_auto_20170829_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitadeacuerdo',
            name='acta_inicio_reportes',
            field=models.FileField(blank=True, null=True, upload_to='visitas/2/reportes/%Y/%m/%d/', verbose_name='Acta de inicio de reportes'),
        ),
        migrations.AlterField(
            model_name='visitadeacuerdo',
            name='cedula_identificacion',
            field=models.FileField(blank=True, null=True, upload_to='visitas/2/identificacion/%Y/%m/%d/', verbose_name='Cédula de identificación basica'),
        ),
        migrations.AlterField(
            model_name='visitadeacuerdo',
            name='constancia_integracion_comite',
            field=models.FileField(blank=True, null=True, upload_to='visitas/2/comite/%Y/%m/%d/', verbose_name='Constancia de Integración de Comité'),
        ),
    ]
