# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-11 15:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitas', '0017_auto_20170901_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregadebebedero',
            name='sim',
        ),
        migrations.RemoveField(
            model_name='visitaalsitio',
            name='sim',
        ),
        migrations.RemoveField(
            model_name='visitadeacuerdo',
            name='sim',
        ),
        migrations.AddField(
            model_name='entregadebebedero',
            name='si',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='si_entrega_bebedero', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitaalsitio',
            name='si',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='si_primera_visita', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitadeacuerdo',
            name='si',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='si_segunda_visita', to=settings.AUTH_USER_MODEL),
        ),
    ]
