# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-28 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0018_auto_20170911_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitaalsitio',
            name='escuela',
        ),
        migrations.RemoveField(
            model_name='visitaalsitio',
            name='si',
        ),
        migrations.DeleteModel(
            name='VisitaAlSitio',
        ),
    ]
