# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-28 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0020_auto_20170928_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitadeacuerdo',
            name='cedula_identificacion',
            field=models.FileField(default='default.pdf', upload_to='visitas/2/identificacion/%Y/%m/%d/', verbose_name='Cédula de identificación basica'),
        ),
    ]
