# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-28 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0021_auto_20170928_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitadeacuerdo',
            name='constancia_integracion_comite',
            field=models.FileField(default='default.pdf', upload_to='visitas/2/comite/%Y/%m/%d/', verbose_name='Constancia de Integración de Comité'),
        ),
        migrations.AlterField(
            model_name='visitadeacuerdo',
            name='convenio_concertacion',
            field=models.FileField(default='default.pdf', upload_to='visitas/2/concertacion/%Y/%m/%d/', verbose_name='Convenio de concertación de aplicación de recurso'),
        ),
    ]
