# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-28 21:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0023_auto_20170928_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitadeacuerdo',
            name='si',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='si_visita_acuerdo', to=settings.AUTH_USER_MODEL),
        ),
    ]
