# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-29 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0025_auto_20170928_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitadeacuerdo',
            name='cedula_identificacion',
            field=models.FileField(upload_to='visitas/2/identificacion/%Y/%m/%d/', verbose_name='Cédula de identificación básica'),
        ),
    ]
