# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-29 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0026_auto_20170929_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitadeacuerdo',
            name='estimacion',
            field=models.FileField(blank=True, null=True, upload_to='visitas/2/acta/%Y/%m/%d/', verbose_name='Estimación'),
        ),
        migrations.AddField(
            model_name='visitadeacuerdo',
            name='plano_instalacion_electrica',
            field=models.FileField(blank=True, null=True, upload_to='visitas/2/acta/%Y/%m/%d/', verbose_name='Plano de instalación electrica'),
        ),
        migrations.AddField(
            model_name='visitadeacuerdo',
            name='plano_instalacion_hidraulica',
            field=models.FileField(blank=True, null=True, upload_to='visitas/2/acta/%Y/%m/%d/', verbose_name='Plano de instalación hidraulica'),
        ),
        migrations.AddField(
            model_name='visitadeacuerdo',
            name='plano_instalacion_sanitaria',
            field=models.FileField(blank=True, null=True, upload_to='visitas/2/acta/%Y/%m/%d/', verbose_name='Plano de instalación sanitaria'),
        ),
    ]
