# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-29 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0028_auto_20170929_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entregadebebedero',
            old_name='acta_de_funcionamiento',
            new_name='acta_funcionamiento',
        ),
    ]
