# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-29 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0029_auto_20170929_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregadebebedero',
            name='acta_funcionamiento',
            field=models.FileField(upload_to='visitas/3/acta/%Y/%m/%d/', verbose_name='Acta de inicio de funcionamiento'),
        ),
    ]
