# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-02 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0030_auto_20170929_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitadeacuerdo',
            name='memoria_calculo',
            field=models.FileField(blank=True, null=True, upload_to='instalaciones/memorias/%Y/%m/%d/', verbose_name='Memorias de cálculo'),
        ),
    ]
