# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-03 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0031_visitadeacuerdo_memoria_calculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitadeacuerdo',
            name='croquis_modulo',
            field=models.FileField(default='default.pdf', upload_to='visitas/2/croquis/%Y/%m/%d/', verbose_name='Croquis de ubicación de modulo'),
        ),
        migrations.AlterField(
            model_name='visitadeacuerdo',
            name='acta_acuerdos',
            field=models.FileField(upload_to='visitas/2/acta/%Y/%m/%d/', verbose_name='Acta de acuerdos'),
        ),
    ]
