# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-03 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0032_auto_20171003_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitadeacuerdo',
            name='distribucion_planta',
            field=models.FileField(blank=True, null=True, upload_to='visitas/2/acta/%Y/%m/%d/', verbose_name='Distribución en planta'),
        ),
        migrations.AddField(
            model_name='visitadeacuerdo',
            name='plano_conjunto',
            field=models.FileField(blank=True, null=True, upload_to='visitas/2/acta/%Y/%m/%d/', verbose_name='Plano de conjunto'),
        ),
        migrations.AlterField(
            model_name='visitadeacuerdo',
            name='memoria_calculo',
            field=models.FileField(blank=True, null=True, upload_to='instalaciones/memorias/%Y/%m/%d/', verbose_name='Memoria de cálculo hidrosanitario y eléctrico'),
        ),
        migrations.AlterField(
            model_name='visitadeacuerdo',
            name='plano_instalacion_hidraulica',
            field=models.FileField(blank=True, null=True, upload_to='visitas/2/acta/%Y/%m/%d/', verbose_name='Plano de instalación hidraulica con isométrico'),
        ),
        migrations.AlterField(
            model_name='visitadeacuerdo',
            name='plano_instalacion_sanitaria',
            field=models.FileField(blank=True, null=True, upload_to='visitas/2/acta/%Y/%m/%d/', verbose_name='Plano de instalación sanitaria  con isométrico'),
        ),
    ]
