# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-05 04:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0033_auto_20171003_1155'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntregaDeBebedero',
            new_name='InicioFuncionamiento',
        ),
    ]
