# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-05 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0034_auto_20171004_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iniciofuncionamiento',
            name='convenio_responsabilidades',
        ),
        migrations.AlterField(
            model_name='iniciofuncionamiento',
            name='video',
            field=models.FileField(upload_to='visitas/3/video/%Y/%m/%d/', verbose_name='Video de muestra del funcionamiento'),
        ),
    ]
