# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-08 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0035_auto_20171004_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitadeacuerdo',
            name='estimacion',
        ),
    ]
