# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-27 14:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitas', '0036_remove_visitadeacuerdo_estimacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaEntrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acta_entrega', models.FileField(upload_to='trabajos/entrega/acta/%Y/%m/%d/', verbose_name='Acta de entrega')),
                ('escuela', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('si', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='si_acta_entrega', to=settings.AUTH_USER_MODEL, verbose_name='Superintendente')),
            ],
            options={
                'verbose_name_plural': 'Inicio de trabajos',
                'ordering': ['escuela'],
            },
        ),
    ]
