# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-27 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0037_actaentrega'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actaentrega',
            options={'ordering': ['escuela'], 'verbose_name_plural': 'Actas de entrega'},
        ),
    ]
