# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-28 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0038_auto_20171027_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actaentrega',
            name='acta_entrega',
            field=models.FileField(upload_to='entrega/actas/%Y/%m/%d/', verbose_name='Acta de entrega'),
        ),
        migrations.AlterField(
            model_name='iniciofuncionamiento',
            name='acta_funcionamiento',
            field=models.FileField(upload_to='funcionamiento/actas/%Y/%m/%d/', verbose_name='Acta de inicio de funcionamiento'),
        ),
        migrations.AlterField(
            model_name='iniciofuncionamiento',
            name='video',
            field=models.FileField(upload_to='funcionamiento/videos/%Y/%m/%d/', verbose_name='Video de muestra del funcionamiento'),
        ),
        migrations.AlterField(
            model_name='visitadeacuerdo',
            name='acta_acuerdos',
            field=models.FileField(upload_to='visitas/actas/%Y/%m/%d/', verbose_name='Acta de acuerdos'),
        ),
        migrations.AlterField(
            model_name='visitadeacuerdo',
            name='cedula_identificacion',
            field=models.FileField(upload_to='visita/identificaciones/%Y/%m/%d/', verbose_name='Cédula de identificación básica'),
        ),
        migrations.AlterField(
            model_name='visitadeacuerdo',
            name='constancia_integracion_comite',
            field=models.FileField(upload_to='visitas/comites/%Y/%m/%d/', verbose_name='Constancia de Integración de Comité'),
        ),
        migrations.AlterField(
            model_name='visitadeacuerdo',
            name='convenio_concertacion',
            field=models.FileField(upload_to='visita/concertaciones/%Y/%m/%d/', verbose_name='Convenio de concertación de aplicación de recurso'),
        ),
        migrations.AlterField(
            model_name='visitadeacuerdo',
            name='croquis_modulo',
            field=models.FileField(default='default.pdf', upload_to='visitas/croquis/%Y/%m/%d/', verbose_name='Croquis de ubicación de modulo'),
        ),
        migrations.AlterField(
            model_name='visitadeacuerdo',
            name='distribucion_planta',
            field=models.FileField(blank=True, null=True, upload_to='visitas/distribuciones/%Y/%m/%d/', verbose_name='Distribución en planta'),
        ),
        migrations.AlterField(
            model_name='visitadeacuerdo',
            name='plano_conjunto',
            field=models.FileField(blank=True, null=True, upload_to='visitas/planosConjunto/%Y/%m/%d/', verbose_name='Plano de conjunto'),
        ),
        migrations.AlterField(
            model_name='visitadeacuerdo',
            name='plano_instalacion_electrica',
            field=models.FileField(blank=True, null=True, upload_to='visitas/pihs/%Y/%m/%d/', verbose_name='Plano de instalación electrica'),
        ),
        migrations.AlterField(
            model_name='visitadeacuerdo',
            name='plano_instalacion_hidraulica',
            field=models.FileField(blank=True, null=True, upload_to='visitas/pies/%Y/%m/%d/', verbose_name='Plano de instalación hidraulica con isométrico'),
        ),
        migrations.AlterField(
            model_name='visitadeacuerdo',
            name='plano_instalacion_sanitaria',
            field=models.FileField(blank=True, null=True, upload_to='visitas/piss/%Y/%m/%d/', verbose_name='Plano de instalación sanitaria  con isométrico'),
        ),
    ]
