# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-30 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0039_auto_20171027_2307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iniciofuncionamiento',
            options={'ordering': ['escuela'], 'verbose_name_plural': 'Inicios de funcionamiento'},
        ),
        migrations.AlterField(
            model_name='iniciofuncionamiento',
            name='acta_funcionamiento',
            field=models.FileField(upload_to='funcionamiento/actas/%Y/%m/%d/', verbose_name='Acta'),
        ),
        migrations.AlterField(
            model_name='iniciofuncionamiento',
            name='video',
            field=models.FileField(upload_to='funcionamiento/videos/%Y/%m/%d/', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='visitadeacuerdo',
            name='constancia_integracion_comite',
            field=models.FileField(upload_to='visitas/comites/%Y/%m/%d/', verbose_name='Constancia de integración de comité'),
        ),
        migrations.AlterField(
            model_name='visitadeacuerdo',
            name='croquis_modulo',
            field=models.FileField(default='default.pdf', upload_to='visitas/croquis/%Y/%m/%d/', verbose_name='Croquis de ubicación de módulo'),
        ),
        migrations.AlterField(
            model_name='visitadeacuerdo',
            name='plano_instalacion_electrica',
            field=models.FileField(blank=True, null=True, upload_to='visitas/pihs/%Y/%m/%d/', verbose_name='Plano de instalación eléctrica'),
        ),
        migrations.AlterField(
            model_name='visitadeacuerdo',
            name='plano_instalacion_hidraulica',
            field=models.FileField(blank=True, null=True, upload_to='visitas/pies/%Y/%m/%d/', verbose_name='Plano de instalación hidráulica con isométrico'),
        ),
    ]
