# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-06 02:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0040_auto_20171029_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actaentrega',
            name='si',
        ),
        migrations.RemoveField(
            model_name='iniciofuncionamiento',
            name='si',
        ),
        migrations.RemoveField(
            model_name='visitadeacuerdo',
            name='si',
        ),
    ]
