# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-07 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0041_auto_20171105_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='actaentrega',
            name='creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
    ]
