# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-20 15:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0042_actaentrega_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitadeacuerdo',
            name='escuela',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escuela_visita_acuerdo', to=settings.AUTH_USER_MODEL),
        ),
    ]
