# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-20 16:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0043_auto_20171120_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iniciofuncionamiento',
            name='escuela',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escuela_inicio_funcionamiento', to=settings.AUTH_USER_MODEL),
        ),
    ]
