# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-20 16:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0045_auto_20171120_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actaentrega',
            name='escuela',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escuela_acta_entrega', to=settings.AUTH_USER_MODEL),
        ),
    ]
