# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-01 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0047_auto_20171201_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitadeacuerdo',
            name='constancia_integracion_comite',
            field=models.FileField(blank=True, null=True, upload_to='visitas/comites/%Y/%m/%d/', verbose_name='Constancia de integración de comité'),
        ),
    ]
