# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-01 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0048_auto_20171201_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitadeacuerdo',
            name='croquis_modulo',
            field=models.FileField(blank=True, null=True, upload_to='visitas/croquis/%Y/%m/%d/', verbose_name='Croquis de ubicación de módulo'),
        ),
    ]
