# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-01 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0049_auto_20171201_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitadeacuerdo',
            name='acta_acuerdos',
        ),
        migrations.RemoveField(
            model_name='visitadeacuerdo',
            name='cedula_identificacion',
        ),
        migrations.AlterField(
            model_name='visitadeacuerdo',
            name='convenio_concertacion',
            field=models.FileField(blank=True, null=True, upload_to='visita/concertaciones/%Y/%m/%d/', verbose_name='Convenio de concertación de aplicación de recurso'),
        ),
    ]
