# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-27 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0050_auto_20171201_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitadeacuerdo',
            name='cedula_identificacion',
            field=models.FileField(blank=True, null=True, upload_to='visita/cedulas/%Y/%m/%d/', verbose_name='Cédula de identificación'),
        ),
        migrations.AlterField(
            model_name='visitadeacuerdo',
            name='convenio_concertacion',
            field=models.FileField(blank=True, null=True, upload_to='visitas/concertaciones/%Y/%m/%d/', verbose_name='Convenio de concertación de aplicación de recurso'),
        ),
    ]
