# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-27 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0051_auto_20171227_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='iniciofuncionamiento',
            name='recibo_llaves',
            field=models.FileField(blank=True, null=True, upload_to='funcionamiento/recibos/%Y/%m/%d/', verbose_name='Recibo de llaves'),
        ),
    ]
