# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-17 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0052_iniciofuncionamiento_recibo_llaves'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitadeacuerdo',
            name='acta_ubicacion',
            field=models.FileField(blank=True, null=True, upload_to='visita/actas/%Y/%m/%d/', verbose_name='Acta de ubicación de bebedero'),
        ),
    ]
