# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-29 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0053_visitadeacuerdo_acta_ubicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitadeacuerdo',
            name='croquis_modulo',
        ),
        migrations.RemoveField(
            model_name='visitadeacuerdo',
            name='memoria_calculo',
        ),
        migrations.RemoveField(
            model_name='visitadeacuerdo',
            name='plano_instalacion_electrica',
        ),
        migrations.RemoveField(
            model_name='visitadeacuerdo',
            name='plano_instalacion_hidraulica',
        ),
        migrations.RemoveField(
            model_name='visitadeacuerdo',
            name='plano_instalacion_sanitaria',
        ),
        migrations.AddField(
            model_name='visitadeacuerdo',
            name='isometrico_instalacion',
            field=models.FileField(blank=True, null=True, upload_to='visitas/pihs/%Y/%m/%d/', verbose_name='Isometricos de instalaciones'),
        ),
        migrations.AddField(
            model_name='visitadeacuerdo',
            name='memoria_calculo_1',
            field=models.FileField(blank=True, null=True, upload_to='instalaciones/memorias/%Y/%m/%d/', verbose_name='Memoria de cálculo hidraulico'),
        ),
        migrations.AddField(
            model_name='visitadeacuerdo',
            name='memoria_calculo_2',
            field=models.FileField(blank=True, null=True, upload_to='instalaciones/memorias/%Y/%m/%d/', verbose_name='Memoria de cálculo sanitario'),
        ),
        migrations.AddField(
            model_name='visitadeacuerdo',
            name='memoria_calculo_3',
            field=models.FileField(blank=True, null=True, upload_to='instalaciones/memorias/%Y/%m/%d/', verbose_name='Memoria de cálculo eléctrico'),
        ),
    ]
