# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-19 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0055_auto_20180227_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iniciofuncionamiento',
            name='acta_funcionamiento',
            field=models.FileField(blank=True, null=True, upload_to='funcionamiento/actas/%Y/%m/%d/', verbose_name='Acta'),
        ),
        migrations.AlterField(
            model_name='iniciofuncionamiento',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='funcionamiento/videos/%Y/%m/%d/', verbose_name='Video'),
        ),
    ]
