# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-29 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0056_auto_20180619_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iniciofuncionamiento',
            name='video',
        ),
        migrations.AddField(
            model_name='iniciofuncionamiento',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='funcionamiento/fotos/%Y/%m/%d/', verbose_name='Evidencia fotográfica'),
        ),
    ]
