# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-05 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0057_auto_20180629_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='iniciofuncionamiento',
            name='foto_2',
            field=models.FileField(blank=True, null=True, upload_to='funcionamiento/fotos/%Y/%m/%d/', verbose_name='Evidencia fotográfica 2'),
        ),
        migrations.AddField(
            model_name='iniciofuncionamiento',
            name='foto_3',
            field=models.FileField(blank=True, null=True, upload_to='funcionamiento/fotos/%Y/%m/%d/', verbose_name='Evidencia fotográfica 3'),
        ),
        migrations.AlterField(
            model_name='iniciofuncionamiento',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='funcionamiento/fotos/%Y/%m/%d/', verbose_name='Evidencia fotográfica 1'),
        ),
    ]
