# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-15 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0058_auto_20180705_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iniciofuncionamiento',
            name='creacion',
        ),
        migrations.RemoveField(
            model_name='iniciofuncionamiento',
            name='recibo_llaves',
        ),
        migrations.AddField(
            model_name='iniciofuncionamiento',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='iniciofuncionamiento',
            name='acta_funcionamiento',
            field=models.FileField(blank=True, null=True, upload_to='funcionamiento/actas/%Y/%m/%d/', verbose_name='Acta de Inicio de Construcción'),
        ),
        migrations.AlterField(
            model_name='iniciofuncionamiento',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='funcionamiento/fotos/%Y/%m/%d/', verbose_name='Foto de entrega con las autoridades correspondientes'),
        ),
        migrations.AlterField(
            model_name='iniciofuncionamiento',
            name='foto_2',
            field=models.FileField(blank=True, null=True, upload_to='funcionamiento/fotos/%Y/%m/%d/', verbose_name='Foto panoramica'),
        ),
        migrations.AlterField(
            model_name='iniciofuncionamiento',
            name='foto_3',
            field=models.FileField(blank=True, null=True, upload_to='funcionamiento/fotos/%Y/%m/%d/', verbose_name='Foto de sistema instalado'),
        ),
    ]
