# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-15 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0059_auto_20181015_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iniciofuncionamiento',
            name='acta_funcionamiento',
            field=models.FileField(blank=True, null=True, upload_to='funcionamiento/actas/%Y/%m/%d/', verbose_name='Acta de Inicio de funcionamiento'),
        ),
        migrations.AlterField(
            model_name='iniciofuncionamiento',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de inicio'),
        ),
    ]
