# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-15 19:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0060_auto_20181015_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iniciofuncionamiento',
            name='fecha',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de inicio'),
        ),
    ]
