# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-15 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0061_auto_20181015_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iniciofuncionamiento',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de inicio'),
        ),
    ]
