# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-29 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0064_auto_20181015_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitadeacuerdo',
            name='constancia_integracion_comite',
        ),
    ]
