# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-29 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0065_remove_visitadeacuerdo_constancia_integracion_comite'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitadeacuerdo',
            name='levantamiento_instalacion',
            field=models.FileField(blank=True, null=True, upload_to='visitas/pihs/%Y/%m/%d/', verbose_name='Levantamiento de instalaciones'),
        ),
    ]
