# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-04 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0066_visitadeacuerdo_levantamiento_instalacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitadeacuerdo',
            name='levantamiento_instalacion',
            field=models.FileField(blank=True, null=True, upload_to='visitas/pihs/%Y/%m/%d/', verbose_name='Levantamiento de instalación'),
        ),
    ]
