# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 18:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partida', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('slug', models.SlugField(null=True)),
                ('imagen', models.ImageField(default='img_no_disponible.jpg', upload_to='estados/%Y/%m/%d/')),
            ],
            options={
                'ordering': ['region', 'partida'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('slug', models.SlugField(null=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Entidad')),
            ],
            options={
                'ordering': ['entidad', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Administrador', 'Administrador'), ('Residente', 'Residente'), ('SIM', 'SIM'), ('Ejecutora', 'Ejecutora'), ('Escuela', 'Escuela')], max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad_de_alumnos', models.IntegerField(blank=True, null=True)),
                ('director', models.CharField(blank=True, max_length=100, null=True)),
                ('representante_legal', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Municipio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.AddField(
            model_name='entidad',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Region'),
        ),
    ]
