# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entidad',
            options={'ordering': ['region', 'partida'], 'verbose_name_plural': 'Entidades'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['numero'], 'verbose_name_plural': 'Regiones'},
        ),
    ]
