# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170611_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='referencias',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Region', verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono'),
        ),
    ]
