# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170615_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='nivel_educativo',
            field=models.CharField(blank=True, choices=[('Preescolar', 'Preescolar'), ('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Media Superior', 'Media Superior'), ('Superior', 'Superior')], max_length=20, null=True),
        ),
    ]
