# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_perfil_nivel_educativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='color',
            field=models.CharField(default='#FFF', max_length=10),
        ),
    ]
