# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-15 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170715_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='cantidad_de_alumnos',
            new_name='aulas_en_uso',
        ),
        migrations.AddField(
            model_name='perfil',
            name='aulas_existentes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='clave',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='conexion',
            field=models.CharField(blank=True, choices=[('Red Municipal', 'Red Municipal'), ('No especificado', 'No especificado')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='plantilla_escolar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='turno',
            field=models.CharField(blank=True, choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino')], max_length=20, null=True),
        ),
    ]
