# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170715_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='foto_director',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/director/%Y/%m/%d/'),
        ),
    ]
