# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_perfil_foto_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='status',
            field=models.CharField(default='por definir', max_length=20),
        ),
    ]
