# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20170718_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Region', verbose_name='Región')),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='entidad',
            options={'ordering': ['partida'], 'verbose_name_plural': 'Entidades'},
        ),
        migrations.AlterModelOptions(
            name='municipio',
            options={'ordering': ['nombre']},
        ),
        migrations.RemoveField(
            model_name='entidad',
            name='region',
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='entidad',
        ),
        migrations.AlterField(
            model_name='entidad',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Partida'),
        ),
        migrations.AddField(
            model_name='zona',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Entidad'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='zona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Zona'),
        ),
    ]
