# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-26 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20170725_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='color',
            field=models.CharField(default='#fff', max_length=30),
        ),
    ]
