# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_zona_sim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Residente', 'Residente'), ('SIM', 'SIM'), ('Ejecutora', 'Ejecutora'), ('Escuela', 'Escuela'), ('Laboratorio', 'Laboratorio')], max_length=30),
        ),
    ]
