# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20170727_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['user'], 'verbose_name_plural': 'Perfiles'},
        ),
    ]
