# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20170727_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='número'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='numero',
            field=models.IntegerField(verbose_name='número'),
        ),
    ]
