# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 17:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0016_auto_20170728_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='representante_inifed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Residente', 'Residente'), ('SIM', 'SIM'), ('Ejecutora', 'Ejecutora'), ('Escuela', 'Escuela'), ('Laboratorio', 'Laboratorio'), ('INIFED Estatal', 'INIFED Estatal')], max_length=30),
        ),
    ]
