# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-22 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20170731_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('SIM', 'SIM'), ('Ejecutora', 'Ejecutora'), ('Escuela', 'Escuela'), ('Laboratorio', 'Laboratorio'), ('INIFED', 'INIFED')], max_length=30),
        ),
    ]
