# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-22 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20170822_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='avance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
