# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-22 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20170822_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='clave',
        ),
    ]
