# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-29 17:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_perfil_clave'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entidad',
            options={'ordering': ['partida', 'nombre'], 'verbose_name_plural': 'Entidades'},
        ),
        migrations.AlterModelOptions(
            name='partida',
            options={'ordering': ['region', 'numero']},
        ),
        migrations.AlterModelOptions(
            name='zona',
            options={'ordering': ['entidad', 'nombre']},
        ),
        migrations.AlterField(
            model_name='entidad',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='zona',
            name='color',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='zona',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre o número'),
        ),
        migrations.AlterField(
            model_name='zona',
            name='sim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='SIM'),
        ),
    ]
