# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-29 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20170829_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('SIM', 'SIM'), ('Ejecutora', 'Ejecutora'), ('Escuela', 'Escuela'), ('Laboratorio', 'Laboratorio'), ('INIFED', 'INIFED'), ('IMTA', 'IMTA'), ('ECA', 'Residente Técnico de Calidad de Agua')], max_length=30),
        ),
    ]
