# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-31 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20170829_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='nombre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
