# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-01 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_region_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='nombre',
        ),
    ]
