# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-01 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_region_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='nombre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
