# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-05 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20170904_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='escuelas_asignadas',
            field=models.IntegerField(default=0),
        ),
    ]
