# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-05 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_entidad_escuelas_asignadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='escuelas_aceptadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='municipio',
            name='escuelas_registradas',
            field=models.IntegerField(default=0),
        ),
    ]
