# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20170905_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='cantidad_entidades',
            field=models.IntegerField(default=1),
        ),
    ]
