# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-08 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_partida_cantidad_entidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='escuelas_aceptadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entidad',
            name='escuelas_registradas',
            field=models.IntegerField(default=0),
        ),
    ]
