# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-08 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20170908_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='escuelas_pendientes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='municipio',
            name='escuelas_rechazadas',
            field=models.IntegerField(default=0),
        ),
    ]
