# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-08 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20170908_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='escuelas_pendientes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entidad',
            name='escuelas_rechazadas',
            field=models.IntegerField(default=0),
        ),
    ]
