# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-11 14:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0034_auto_20170908_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zona',
            name='sim',
        ),
        migrations.AddField(
            model_name='partida',
            name='si',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Superintendente'),
        ),
    ]
