# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-11 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20170911_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entidad',
            old_name='representante_inifed',
            new_name='coordinador_estatal',
        ),
    ]
