# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-11 15:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0036_auto_20170911_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='residente_tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residente_tecnico', to=settings.AUTH_USER_MODEL, verbose_name='Residente Técnico'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='coordinador_estatal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinador_estatal', to=settings.AUTH_USER_MODEL, verbose_name='Coordinador Estatal'),
        ),
    ]
