# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-27 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20170911_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='cantidad_entidades',
        ),
        migrations.AlterField(
            model_name='region',
            name='nombre',
            field=models.CharField(default='Default', max_length=20),
        ),
    ]
