# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-28 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_auto_20170928_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escuela_municipio', to='accounts.Municipio'),
        ),
    ]
