# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-30 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_auto_20170928_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='SSID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='clave_SSID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto_escuela',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/escuela/%Y/%m/%d/', verbose_name='Foto de la entrada de la escuela'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto_director',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/director/%Y/%m/%d/', verbose_name='Foto del director'),
        ),
    ]
