# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-02 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_auto_20170930_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='localidad',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='domicilio',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
