# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-03 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_auto_20171002_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='aulas_en_uso',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='aulas_existentes',
        ),
    ]
