# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-04 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_auto_20171003_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/qr/%Y/%m/%d/', verbose_name='Código QR'),
        ),
    ]
