# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-04 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_perfil_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='qr',
            field=models.FileField(blank=True, null=True, upload_to='fotos/qr/%Y/%m/%d/', verbose_name='Código QR'),
        ),
    ]
