# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-05 01:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_auto_20171004_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='qr',
            new_name='qrcode',
        ),
    ]
