# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-05 19:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0051_auto_20171004_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='laboratorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laboratorio', to=settings.AUTH_USER_MODEL, verbose_name='Residente Técnico'),
        ),
    ]
