# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-05 22:03
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_entidad_laboratorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='position',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42, null=True),
        ),
    ]
