# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-05 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_perfil_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='position',
            new_name='coordenadas',
        ),
    ]
