# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-17 16:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_auto_20171006_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='laboratorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laboratorio', to=settings.AUTH_USER_MODEL, verbose_name='Laboratorio'),
        ),
    ]
