# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-17 16:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_auto_20171017_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='residente_tecnico',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residente_tecnico', to=settings.AUTH_USER_MODEL, verbose_name='Residente Técnico'),
        ),
    ]
