# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-17 17:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0061_auto_20171017_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='superintendente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superintendente', to=settings.AUTH_USER_MODEL),
        ),
    ]
