# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-24 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_auto_20171018_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidad',
            name='residente_tecnico',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='qrcode',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('SI', 'Superintendente'), ('Ejecutora', 'Ejecutora'), ('Escuela', 'Escuela'), ('Laboratorio', 'Laboratorio'), ('INIFED', 'INIFED'), ('CEstatal', 'Coordinador Estatal de INIFED'), ('IMTA', 'IMTA'), ('PQ', 'Procesos Químicos (Calidad de Agua)'), ('PM', 'Planta y Manufactura')], max_length=30),
        ),
        migrations.AlterField(
            model_name='region',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
