# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-29 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_auto_20171024_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='si',
        ),
    ]
