# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-01 21:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0065_remove_partida_si'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='region',
        ),
        migrations.RemoveField(
            model_name='entidad',
            name='coordinador_estatal',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='conexion',
        ),
        migrations.RemoveField(
            model_name='zona',
            name='superintendente',
        ),
        migrations.AddField(
            model_name='entidad',
            name='coordinador_estatal_inifed',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinador_estatal_inifed', to=settings.AUTH_USER_MODEL, verbose_name='Coordinador Estatal de INIFED'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Region', verbose_name='Región'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='residente_obra',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residente_obra', to=settings.AUTH_USER_MODEL, verbose_name='Residente de Obra'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='residente_tecnico_inifed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residente_tecnico_inifed', to=settings.AUTH_USER_MODEL, verbose_name='Residente Técnico de INIFED'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='partida',
            field=models.IntegerField(verbose_name='número'),
        ),
        migrations.DeleteModel(
            name='Partida',
        ),
    ]
