# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-01 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_auto_20171101_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='representante_legal',
        ),
        migrations.AddField(
            model_name='perfil',
            name='funcion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Función'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Region', verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Ejecutora', 'Ejecutora'), ('Escuela', 'Escuela'), ('Laboratorio', 'Laboratorio'), ('INIFED', 'INIFED'), ('IMTA', 'IMTA'), ('PQ', 'Procesos Químicos (Calidad de Agua)'), ('PM', 'Planta y Manufactura')], max_length=30),
        ),
    ]
