# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-01 23:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0067_auto_20171101_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidad',
            name='residente_tecnico_inifed',
        ),
        migrations.AddField(
            model_name='entidad',
            name='sim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sim', to=settings.AUTH_USER_MODEL, verbose_name='Superintendente de mantenimiento'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='residente_tecnico_inifed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residente_tecnico_estatal', to='accounts.Entidad', verbose_name='Es residente estatal INIFED de'),
        ),
    ]
