# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-03 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_auto_20171101_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='funcion',
        ),
        migrations.AddField(
            model_name='perfil',
            name='cargo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Cargo'),
        ),
    ]
