# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-03 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0069_auto_20171103_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cargo',
            field=models.CharField(blank=True, choices=[('CEINIFED', 'Coordinador Estatal de INIFED'), ('RTINIFED', 'Residente Técnico de INIFED'), ('ROCarsev', 'Residente de Obra'), ('SIM', 'SIM')], max_length=30, null=True, verbose_name='Cargo'),
        ),
    ]
