# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-06 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0071_auto_20171105_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cargo',
            field=models.CharField(blank=True, choices=[('CEINIFED', 'Coordinador Estatal de INIFED'), ('RTINIFED', 'Residente Técnico de INIFED'), ('RO', 'Residente de Obra'), ('SIM', 'Superintendente')], max_length=30, null=True, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nivel_educativo',
            field=models.CharField(blank=True, choices=[('Preescolar', 'Preescolar'), ('Primaria', 'Primaria'), ('Secundaria', 'Secundaria')], max_length=20, null=True),
        ),
    ]
