# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-07 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0072_auto_20171106_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='mantenimientos',
            field=models.IntegerField(default=0),
        ),
    ]
