# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-08 03:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0074_auto_20171107_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='coordinador_regional_inifed',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinador_regional_inifed', to=settings.AUTH_USER_MODEL, verbose_name='Coordinador Regional de INIFED'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cargo',
            field=models.CharField(blank=True, choices=[('CEINIFED', 'Coordinador Estatal de INIFED'), ('RTINIFED', 'Residente Técnico de INIFED'), ('CRINIFED', 'Coordinador Regional de INIFED'), ('RO', 'Residente de Obra'), ('SIM', 'Superintendente')], max_length=30, null=True, verbose_name='Cargo'),
        ),
    ]
