# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-16 18:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0078_auto_20171112_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='enlace_institucional_inifed',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enlace_institucional_inifed', to=settings.AUTH_USER_MODEL, verbose_name='Enlace Institucional de INIFED'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cargo',
            field=models.CharField(blank=True, choices=[('INIFED', (('CRINIFED', 'Coordinador Regional'), ('EIINIFED', 'Enlace Institucional'), ('CEINIFED', 'Coordinador Estatal'), ('RTINIFED', 'Residente Técnico'))), ('Ejecutora', (('RO', 'Residente de Obra'), ('SIM', 'Superintendente')))], max_length=30, null=True, verbose_name='Cargo'),
        ),
    ]
