# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-27 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0079_auto_20171116_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Ejecutora', 'Ejecutora'), ('Escuela', 'Escuela'), ('Laboratorio', 'Laboratorio'), ('INIFED', 'INIFED'), ('PQ', 'Procesos Químicos (Calidad de Agua)'), ('PM', 'Planta y Manufactura')], max_length=30),
        ),
    ]
