# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-29 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0080_auto_20171127_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipio',
            name='escuelas_aceptadas',
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='escuelas_pendientes',
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='escuelas_rechazadas',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='status',
        ),
    ]
