# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-29 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0081_auto_20171129_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidad',
            name='escuelas_aceptadas',
        ),
        migrations.RemoveField(
            model_name='entidad',
            name='escuelas_pendientes',
        ),
        migrations.RemoveField(
            model_name='entidad',
            name='escuelas_rechazadas',
        ),
    ]
