# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-05 15:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0082_auto_20171129_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidad',
            name='residente_obra',
        ),
        migrations.AddField(
            model_name='entidad',
            name='superintendente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superintendente', to=settings.AUTH_USER_MODEL, verbose_name='Superintendente'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='residente_tecnico_ejecutora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residente_tecnico_ejecutora', to='accounts.Entidad', verbose_name='Es residente estatal ejecutora del estado de'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='residente_tecnico_inifed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residente_tecnico_inifed', to='accounts.Entidad', verbose_name='Es residente estatal de INIFED del estado de'),
        ),
    ]
