# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-05 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0083_auto_20171205_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cargo',
            field=models.CharField(blank=True, choices=[('INIFED', (('CRINIFED', 'Coordinador Regional'), ('EIINIFED', 'Enlace Institucional'), ('CEINIFED', 'Coordinador Estatal'), ('RTINIFED', 'Residente Técnico'))), ('Ejecutora', (('SIM', 'Superintendente de Mantenimiento'), ('SI', 'Superintendente'), ('RO', 'Residente de Obra')))], max_length=30, null=True, verbose_name='Cargo'),
        ),
    ]
