# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-05 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0084_auto_20171205_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='residente_tecnico_ejecutora',
        ),
        migrations.AddField(
            model_name='perfil',
            name='residente_obra_ejecutora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residente_obra_ejecutora', to='accounts.Entidad', verbose_name='Es residente de obra de la ejecutora del estado de'),
        ),
    ]
