# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-07 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0085_auto_20171205_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='foto_director',
        ),
    ]
