# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-27 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0087_auto_20171219_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='t7',
            field=models.FileField(blank=True, null=True, upload_to='t7/%Y/%m/%d/', verbose_name='Archivo(s) de T7'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='turno',
            field=models.CharField(blank=True, choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino'), ('Tiempo Completo', 'Tiempo Completo')], max_length=20, null=True),
        ),
    ]
