# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-02 18:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0088_auto_20171227_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='sim',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sim', to=settings.AUTH_USER_MODEL, verbose_name='Superintendente de mantenimiento'),
        ),
    ]
