# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-15 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0089_auto_20180402_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='evidencias',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
