# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-07 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0093_perfil_expediente_tecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='prioridad',
            field=models.BooleanField(default=False, verbose_name='Prioridad de construcción'),
        ),
    ]
