# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-09 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0095_perfil_ultima_foto_construccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='ultima_foto_construccion',
            new_name='nombre_ultima_evidencia',
        ),
    ]
