# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-31 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0096_auto_20181009_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
