# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-29 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0097_perfil_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidad',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='entidad',
            name='t7',
        ),
        migrations.AddField(
            model_name='entidad',
            name='doc1',
            field=models.FileField(blank=True, null=True, upload_to='doc/%Y/%m/%d/', verbose_name='D1'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='doc2',
            field=models.FileField(blank=True, null=True, upload_to='doc/%Y/%m/%d/', verbose_name='D2'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='doc3',
            field=models.FileField(blank=True, null=True, upload_to='doc/%Y/%m/%d/', verbose_name='D3'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='fecha_doc1',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de subida'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='fecha_doc2',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de subida'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='fecha_doc3',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de subida'),
        ),
    ]
