# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-29 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0098_auto_20181229_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='doc1',
            field=models.FileField(blank=True, null=True, upload_to='doc/%Y/%m/%d/', verbose_name='Informe de respuesta de a Oficio'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='doc2',
            field=models.FileField(blank=True, null=True, upload_to='doc/%Y/%m/%d/', verbose_name='Solicitud de diferimiento'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='doc3',
            field=models.FileField(blank=True, null=True, upload_to='doc/%Y/%m/%d/', verbose_name='Solicitud de cartas de inicio y convenios de concertación'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='fecha_doc1',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de subida del Informe de respuesta de a Oficio'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='fecha_doc2',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de subida de la solicitud de diferimiento'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='fecha_doc3',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de subida de solicitud de cartas de inicio y convenios de concertación'),
        ),
    ]
