# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-27 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0099_auto_20181229_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='expediente_completo',
            field=models.FileField(blank=True, null=True, upload_to='doc/%Y/%m/%d/', verbose_name='Expediente completo'),
        ),
    ]
