# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 19:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InicioDeTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acta_de_inicio', models.FileField(upload_to='trabajos/inicio/acta/%Y/%m/%d/', verbose_name='Acta de inicios de trabajos')),
                ('hoja_de_cotizacion', models.FileField(upload_to='visitas/1/cotizacion/%Y/%m/%d/', verbose_name='Hoja de cotizaciones')),
                ('escuela', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sim_inicio_trabajo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['escuela'],
                'verbose_name_plural': 'Inicio de trabajos',
            },
        ),
        migrations.CreateModel(
            name='InstalacionDeSB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporte', models.FileField(upload_to='instalaciones/reporte/%Y/%m/%d/', verbose_name='Reporte de instalación')),
                ('plantilla_fotografica', models.FileField(upload_to='instalaciones/plantilla/%Y/%m/%d/', verbose_name='Plantilla fotográfica de su instalación y funcionamiento')),
                ('recepcion_de_mueble_bebedero', models.FileField(upload_to='instalaciones/recepcion/%Y/%m/%d/', verbose_name='Recepción del mueble bebedero y sus componentes')),
                ('escuela', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_instalacion_sb', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['escuela'],
                'verbose_name_plural': 'Instalaciones de Sistemas bebedero',
            },
        ),
        migrations.CreateModel(
            name='TerminoDeTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporte_de_segunda_toma', models.FileField(upload_to='visitas/2/reporte_de_toma/%Y/%m/%d/', verbose_name='Reporte de segunda toma de muestra')),
                ('plantilla_fotografica', models.FileField(upload_to='instalaciones/plantilla/%Y/%m/%d/', verbose_name='Plantilla fotográfica de su instalación y funcionamiento')),
                ('escuela', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sim_termino_trabajo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['escuela'],
                'verbose_name_plural': 'Terminos de trabajo',
            },
        ),
    ]
