# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstalacionDeSB',
            new_name='InstalacionBebedero',
        ),
    ]
