# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0002_auto_20170728_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iniciodetrabajo',
            old_name='acta_de_inicio',
            new_name='acta_inicio',
        ),
        migrations.RenameField(
            model_name='iniciodetrabajo',
            old_name='hoja_de_cotizacion',
            new_name='hoja_cotizacion',
        ),
        migrations.RenameField(
            model_name='instalacionbebedero',
            old_name='recepcion_de_mueble_bebedero',
            new_name='recepcion_mueble_bebedero',
        ),
        migrations.RenameField(
            model_name='terminodetrabajo',
            old_name='reporte_de_segunda_toma',
            new_name='reporte_segunda_toma',
        ),
    ]
