# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-10 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0003_auto_20170729_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iniciodetrabajo',
            name='acta_inicio',
            field=models.FileField(upload_to='trabajos/inicio/acta/%Y/%m/%d/', verbose_name='Acta de inicio de trabajo'),
        ),
        migrations.AlterField(
            model_name='iniciodetrabajo',
            name='hoja_cotizacion',
            field=models.FileField(upload_to='visitas/1/cotizacion/%Y/%m/%d/', verbose_name='Hoja de cotización'),
        ),
        migrations.AlterField(
            model_name='instalacionbebedero',
            name='plantilla_fotografica',
            field=models.FileField(upload_to='instalaciones/plantilla/%Y/%m/%d/', verbose_name='Plantilla fotográfica de instalación y funcionamiento'),
        ),
    ]
