# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0004_auto_20170810_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iniciodetrabajo',
            name='hoja_cotizacion',
        ),
    ]
