# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0006_bitacora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitacora',
            name='ejecutora',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='escuela',
        ),
        migrations.DeleteModel(
            name='Bitacora',
        ),
    ]
