# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 22:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('construccion', '0007_auto_20170811_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('Firme', 'Firme'), ('Muro', 'Muro'), ('Techumbre y puerta', 'Techumbre y puerta'), ('Instalación de Mueble Bebedero', 'Instalación de Mueble Bebedero')], max_length=30)),
                ('video', models.FileField(upload_to='instalaciones/bitacotra/video/%Y/%m/%d/', verbose_name='Evidencia audio visual')),
                ('ejecutora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecutora_bitacora', to=settings.AUTH_USER_MODEL)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
