# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-12 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0008_bitacora'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitacora',
            options={'ordering': ['escuela']},
        ),
    ]
