# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-12 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0009_auto_20170812_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instalacionbebedero',
            name='plantilla_fotografica',
        ),
        migrations.AddField(
            model_name='instalacionbebedero',
            name='memoria_calculo',
            field=models.FileField(blank=True, null=True, upload_to='instalaciones/memorias/%Y/%m/%d/', verbose_name='Memorias de calculo'),
        ),
        migrations.AddField(
            model_name='instalacionbebedero',
            name='plano_instalacion',
            field=models.FileField(blank=True, null=True, upload_to='instalaciones/planos/%Y/%m/%d/', verbose_name='Plano de Instalaciones'),
        ),
    ]
