# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-12 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0010_auto_20170812_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacionbebedero',
            name='trabajos_de_conexión',
            field=models.FileField(blank=True, null=True, upload_to='instalaciones/memorias/%Y/%m/%d/', verbose_name='Trabajos de conexión'),
        ),
    ]
