# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-21 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0011_instalacionbebedero_trabajos_de_conexión'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bitacora',
            new_name='EvidenciaConstruccion',
        ),
    ]
