# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-21 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0012_auto_20170821_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenciaconstruccion',
            name='aprobacion',
            field=models.CharField(choices=[('En espera', 'En espera'), ('Aprobado', 'Aprobado'), ('No aprobado', 'No aprobado')], default='En espera', max_length=11, verbose_name='Aprobación'),
        ),
    ]
