# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-21 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0013_evidenciaconstruccion_aprobacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instalacionbebedero',
            old_name='trabajos_de_conexión',
            new_name='trabajos_de_conexion',
        ),
        migrations.AddField(
            model_name='evidenciaconstruccion',
            name='creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
    ]
