# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-29 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0016_notadebitacora_resuelto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instalacionbebedero',
            options={'ordering': ['escuela'], 'verbose_name_plural': 'Instalaciones de Sistemas Bebedero'},
        ),
        migrations.AlterModelOptions(
            name='notadebitacora',
            options={'ordering': ['escuela'], 'verbose_name_plural': 'Notas de bitacora'},
        ),
    ]
