# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-01 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0017_auto_20170829_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidenciaconstruccion',
            name='aprobacion',
        ),
        migrations.AddField(
            model_name='evidenciaconstruccion',
            name='aprobacion_Residente',
            field=models.CharField(choices=[('En espera', 'En espera'), ('Aprobado', 'Aprobado'), ('No aprobado', 'No aprobado')], default='En espera', max_length=11, verbose_name='Aprobación de residente'),
        ),
        migrations.AddField(
            model_name='evidenciaconstruccion',
            name='aprobacion_SI',
            field=models.CharField(choices=[('En espera', 'En espera'), ('Aprobado', 'Aprobado'), ('No aprobado', 'No aprobado')], default='En espera', max_length=11, verbose_name='Aprobación de SI'),
        ),
    ]
