# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-11 15:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('construccion', '0018_auto_20170901_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iniciodetrabajo',
            name='sim',
        ),
        migrations.RemoveField(
            model_name='instalacionbebedero',
            name='sim',
        ),
        migrations.RemoveField(
            model_name='terminodetrabajo',
            name='sim',
        ),
        migrations.AddField(
            model_name='iniciodetrabajo',
            name='si',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='si_inicio_trabajo', to=settings.AUTH_USER_MODEL, verbose_name='Superintendente'),
        ),
        migrations.AddField(
            model_name='instalacionbebedero',
            name='si',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sim_instalacion_sb', to=settings.AUTH_USER_MODEL, verbose_name='Superintendente'),
        ),
        migrations.AddField(
            model_name='terminodetrabajo',
            name='si',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sim_termino_trabajo', to=settings.AUTH_USER_MODEL, verbose_name='Superintendente'),
        ),
    ]
