# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-29 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0022_auto_20170929_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidenciaconstruccion',
            name='aprobacion_Residente',
        ),
    ]
