# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-29 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0024_auto_20170929_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenciaconstruccion',
            name='video',
            field=models.FileField(upload_to='instalaciones/bitacora/video/%Y/%m/%d/', verbose_name='Evidencia audio visual'),
        ),
    ]
