# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-02 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0025_auto_20170929_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notadebitacora',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='notadebitacora',
            name='escuela',
        ),
        migrations.DeleteModel(
            name='NotaDeBitacora',
        ),
    ]
