# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-02 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0026_auto_20171002_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidenciaconstruccion',
            name='ejecutora',
        ),
    ]
