# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-05 03:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0028_auto_20171002_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminodetrabajo',
            name='escuela',
        ),
        migrations.RemoveField(
            model_name='terminodetrabajo',
            name='si',
        ),
        migrations.DeleteModel(
            name='TerminoDeTrabajo',
        ),
    ]
