# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-05 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0029_auto_20171004_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instalacionbebedero',
            name='trabajos_de_conexion',
        ),
    ]
