# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-27 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0031_actaentrega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actaentrega',
            name='escuela',
        ),
        migrations.RemoveField(
            model_name='actaentrega',
            name='si',
        ),
        migrations.DeleteModel(
            name='ActaEntrega',
        ),
    ]
