# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-28 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0032_auto_20171027_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenciaconstruccion',
            name='video',
            field=models.FileField(upload_to='instalaciones/video/%Y/%m/%d/', verbose_name='Evidencia audio visual'),
        ),
        migrations.AlterField(
            model_name='iniciodetrabajo',
            name='acta_inicio',
            field=models.FileField(upload_to='iniciosTrabajo/actas/%Y/%m/%d/', verbose_name='Acta de inicio de trabajo'),
        ),
        migrations.AlterField(
            model_name='instalacionbebedero',
            name='recepcion_mueble_bebedero',
            field=models.FileField(upload_to='instalaciones/recepciones/%Y/%m/%d/', verbose_name='Recepción del mueble bebedero y sus componentes'),
        ),
        migrations.AlterField(
            model_name='instalacionbebedero',
            name='reporte',
            field=models.FileField(upload_to='instalaciones/reportes/%Y/%m/%d/', verbose_name='Reporte de instalación'),
        ),
    ]
