# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-30 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0033_auto_20171027_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenciaconstruccion',
            name='aprobacion_SI',
            field=models.CharField(choices=[('En espera', 'En espera'), ('Aprobado', 'Aprobado'), ('No aprobado', 'No aprobado')], default='En espera', max_length=11, verbose_name='Aprobación del Superintendente'),
        ),
    ]
