# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-06 02:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0034_auto_20171029_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iniciodetrabajo',
            name='si',
        ),
        migrations.RemoveField(
            model_name='instalacionbebedero',
            name='si',
        ),
    ]
