# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-05 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0036_auto_20171117_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenciaconstruccion',
            name='fase',
            field=models.CharField(choices=[('1', 'Trazo'), ('2', 'Excavación, corte y demolición'), ('3', 'Cimbra y habilitado de firme'), ('4', 'Colado de firme'), ('5', 'Muros, castillos y cadenas'), ('6', 'Aplanados, pinturas y rampa'), ('7', 'Estructura y puerta'), ('8', 'Policarbonato'), ('9', 'Mueble bebedero'), ('10', 'Placa de identidad')], max_length=30),
        ),
    ]
