# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-05 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0038_auto_20171205_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenciaconstruccion',
            name='foto',
            field=models.FileField(upload_to='evidencia/foto/%Y/%m/%d/', verbose_name='Fotografía'),
        ),
    ]
