# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-06 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0039_auto_20171205_1701'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnvolventeTerminado',
            new_name='EnvolventeTerminada',
        ),
    ]
