# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-06 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0041_auto_20171206_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenciaconstruccion',
            name='fase',
            field=models.CharField(choices=[('1° Trazo', '1° Trazo'), ('2° Excavación, corte y demolición', '2° Excavación, corte y demolición'), ('3° Cimbra y habilitado de firme', '3° Cimbra y habilitado de firme'), ('4° Colado de firme', '4° Colado de firme'), ('5° Muros, castillos y cadenas', '5° Muros, castillos y cadenas'), ('6° Aplanados, pinturas y rampa', '6° Aplanados, pinturas y rampa'), ('7° Estructura y puerta', '7° Estructura y puerta'), ('8° Policarbonato', '8° Policarbonato'), ('9° Mueble bebedero', '9° Mueble bebedero'), ('10° Placa de identidad', '10° Placa de identidad')], max_length=50),
        ),
    ]
