# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-25 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carnet',
            new_name='Mantenimiento',
        ),
    ]
