# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-25 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_auto_20170825_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento',
            name='sim',
        ),
        migrations.DeleteModel(
            name='Mantenimiento',
        ),
    ]
