# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-01 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0005_auto_20170826_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='volumen',
            field=models.IntegerField(default=0, verbose_name='Volumen indicado en medidor'),
        ),
    ]
