# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-01 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0006_mantenimiento_volumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='descricpcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='tipo',
            field=models.CharField(choices=[('Preventivo', 'Preventivo'), ('Correctivo', 'Correctivo')], default='Preventivo', max_length=20),
        ),
    ]
