# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-01 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0007_auto_20170901_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mantenimiento',
            old_name='descricpcion',
            new_name='descripcion',
        ),
    ]
