# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-11 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0008_auto_20170901_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mantenimiento',
            old_name='sim',
            new_name='si',
        ),
    ]
