# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-27 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0009_auto_20170911_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
