# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-27 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0010_auto_20170927_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='volumen',
            field=models.IntegerField(verbose_name='Volumen indicado en medidor'),
        ),
    ]
