# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-05 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0011_auto_20170927_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='carnet',
            field=models.FileField(upload_to='', verbose_name='Carnet actualizado'),
        ),
    ]
