# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-05 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0012_auto_20171004_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='tipo',
            field=models.CharField(choices=[('Preventivo', 'Preventivo'), ('Correctivo', 'Correctivo'), ('Acta', 'Acta')], default='Preventivo', max_length=20),
        ),
    ]
