# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-05 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0013_auto_20171005_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='tipo',
            field=models.CharField(choices=[('Preventivo', 'Preventivo'), ('Correctivo', 'Correctivo'), ('Acta de entrega', 'Acta de entrega (Mes 24)')], default='Preventivo', max_length=20),
        ),
    ]
