# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-27 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0014_auto_20171005_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='carnet',
            field=models.FileField(upload_to='mantenimientos/%Y/%m/%d/', verbose_name='Carnet actualizado'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='tipo',
            field=models.CharField(choices=[('Preventivo', 'Preventivo'), ('Correctivo', 'Correctivo')], default='Preventivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='volumen',
            field=models.IntegerField(verbose_name='Volumen indicado en medidor (Litros)'),
        ),
    ]
