# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-27 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0015_auto_20171027_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='año',
            field=models.IntegerField(choices=[(2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2020')]),
        ),
    ]
