# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-01 23:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0017_auto_20171029_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='si',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='si_mtto', to=settings.AUTH_USER_MODEL),
        ),
    ]
