# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-12 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0018_auto_20171101_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento',
            name='si',
        ),
    ]
