# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-26 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0019_remove_mantenimiento_si'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mantenimiento',
            options={},
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de mantenimiento'),
        ),
    ]
