# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-26 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0020_auto_20180426_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de mantenimiento'),
        ),
    ]
