# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-05 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0021_auto_20180426_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='foto_mueble',
            field=models.FileField(blank=True, null=True, upload_to='mantenimientos/%Y/%m/%d/', verbose_name='Mueble'),
        ),
    ]
