# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-15 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0022_mantenimiento_foto_mueble'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento',
            name='foto_mueble',
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='foto_1',
            field=models.FileField(blank=True, null=True, upload_to='mantenimientos/%Y/%m/%d/', verbose_name='Foto al iniciar el mantenimiento'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='foto_2',
            field=models.FileField(blank=True, null=True, upload_to='mantenimientos/%Y/%m/%d/', verbose_name='Foto durante mantenimiento'),
        ),
    ]
