# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-29 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0023_auto_20181015_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='foto_3',
            field=models.FileField(blank=True, null=True, upload_to='mantenimientos/%Y/%m/%d/', verbose_name='Foto del medidor'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='foto_2',
            field=models.FileField(blank=True, null=True, upload_to='mantenimientos/%Y/%m/%d/', verbose_name='Foto al finalizar el mantenimiento'),
        ),
    ]
