# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 19:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bebedero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10)),
                ('nivel_educativo', models.CharField(choices=[('Preescolar', 'Preescolar'), ('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Media Superior', 'Media Superior')], max_length=30)),
                ('cantidad_de_boquillas', models.IntegerField()),
                ('cantidad_de_boquillas_discapacidad', models.IntegerField()),
                ('cantidad_de_llenador_de_botellas', models.IntegerField()),
                ('salidas', models.IntegerField()),
                ('rango', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['clave'],
            },
        ),
        migrations.CreateModel(
            name='Filtro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=10)),
                ('litros_de_vida', models.IntegerField()),
                ('presion', models.CharField(max_length=30)),
                ('normas_cumplidas', models.CharField(choices=[('NOM-127-SSA1-1994', 'NOM-127-SSA1-1994'), ('NOM-201-SSA1-2015', 'NOM-201-SSA1-2015'), ('Ambas', 'Ambas'), ('Ninguna', 'Ninguna')], max_length=20)),
            ],
            options={
                'ordering': ['modelo'],
            },
        ),
        migrations.CreateModel(
            name='Mueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['modelo'],
            },
        ),
        migrations.CreateModel(
            name='SistemaBebedero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bebedero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bebedero', to='bebederos.Bebedero')),
                ('constructora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constructora', to=settings.AUTH_USER_MODEL)),
                ('escuela', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escuela', to=settings.AUTH_USER_MODEL)),
                ('filtro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filtro', to='bebederos.Filtro')),
                ('mueble', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mueble', to='bebederos.Mueble')),
            ],
            options={
                'ordering': ['escuela'],
            },
        ),
    ]
