# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sistemabebedero',
            name='mueble',
        ),
        migrations.DeleteModel(
            name='Mueble',
        ),
    ]
