# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0002_auto_20170613_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['modelo'],
            },
        ),
        migrations.AddField(
            model_name='sistemabebedero',
            name='mueble',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mueble', to='bebederos.Mueble'),
        ),
    ]
