# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0006_auto_20170614_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistemabebedero',
            name='mueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mueble', to='bebederos.Mueble'),
        ),
    ]
