# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0007_auto_20170614_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtro',
            name='presion',
            field=models.CharField(max_length=30, verbose_name='Presión'),
        ),
    ]
