# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0008_auto_20170615_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemabebedero',
            name='identificador',
            field=models.IntegerField(default=0),
        ),
    ]
