# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-21 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0009_sistemabebedero_identificador'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemabebedero',
            name='modulo',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=1),
        ),
    ]
