# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-26 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0011_auto_20170726_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sistemapotabilizacion',
            options={'ordering': ['tipo']},
        ),
        migrations.RemoveField(
            model_name='mueble',
            name='rango',
        ),
        migrations.RemoveField(
            model_name='mueble',
            name='salidas',
        ),
        migrations.RemoveField(
            model_name='sistemapotabilizacion',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='sistemapotabilizacion',
            name='presion',
        ),
        migrations.AddField(
            model_name='mueble',
            name='alumnos_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mueble',
            name='alumnos_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sistemapotabilizacion',
            name='descipcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sistemapotabilizacion',
            name='tipo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
