# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0012_auto_20170726_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sistemapotabilizacion',
            options={'ordering': ['tipo'], 'verbose_name_plural': 'Sistemas de Potabilización'},
        ),
    ]
