# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0013_auto_20170727_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sistemabebedero',
            options={'ordering': ['escuela'], 'verbose_name_plural': 'Sistemas bebederos'},
        ),
        migrations.AlterModelOptions(
            name='sistemapotabilizacion',
            options={'ordering': ['tipo'], 'verbose_name_plural': 'Sistemas de potabilización'},
        ),
    ]
