# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0014_auto_20170728_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mueble',
            old_name='cantidad_de_boquillas',
            new_name='cantidad_boquillas',
        ),
        migrations.RenameField(
            model_name='mueble',
            old_name='cantidad_de_boquillas_discapacidad',
            new_name='cantidad_boquillas_discapacidad',
        ),
        migrations.RenameField(
            model_name='mueble',
            old_name='cantidad_de_llenador_de_botellas',
            new_name='cantidad_llenador_de_botellas',
        ),
        migrations.RenameField(
            model_name='sistemapotabilizacion',
            old_name='litros_de_vida',
            new_name='litros_vida',
        ),
    ]
