# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0015_auto_20170728_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sistemabebedero',
            name='identificador',
        ),
        migrations.AddField(
            model_name='sistemabebedero',
            name='identificador_mb',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sistemabebedero',
            name='identificador_sp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Identificador de sistema de potabilización'),
        ),
        migrations.AddField(
            model_name='sistemabebedero',
            name='qr_sp',
            field=models.FileField(blank=True, null=True, upload_to='codigos/sp/%Y/%m/%d/', verbose_name='Codigo QR de sistema de potabilización'),
        ),
        migrations.AlterField(
            model_name='sistemapotabilizacion',
            name='descipcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
