# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0016_auto_20170729_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mueble',
            name='alumnos_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rango maximo de alumnos'),
        ),
        migrations.AlterField(
            model_name='mueble',
            name='alumnos_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rango minimo de alumnos'),
        ),
        migrations.AlterField(
            model_name='sistemabebedero',
            name='identificador_mb',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Identificador de mueble bebedero'),
        ),
    ]
