# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-29 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0018_auto_20170811_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sistemabebedero',
            options={'ordering': ['escuela'], 'verbose_name_plural': 'Sistemas bebedero'},
        ),
    ]
