# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-27 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0020_auto_20170911_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sistemapotabilizacion',
            old_name='descipcion',
            new_name='descripcion',
        ),
        migrations.AlterField(
            model_name='mueble',
            name='nivel_educativo',
            field=models.CharField(choices=[('Preescolar', 'Preescolar'), ('Primaria', 'Primaria'), ('Secundaria', 'Secundaria')], max_length=30),
        ),
    ]
