# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-27 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0021_auto_20170927_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mueble',
            name='alumnos_max',
            field=models.IntegerField(blank=True, default=0, verbose_name='Rango maximo de alumnos'),
        ),
        migrations.AlterField(
            model_name='mueble',
            name='alumnos_min',
            field=models.IntegerField(default=0, verbose_name='Rango minimo de alumnos'),
        ),
    ]
