# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-27 13:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0022_auto_20170927_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mueble',
            name='alumnos_max',
            field=models.IntegerField(verbose_name='Rango maximo de alumnos'),
        ),
        migrations.AlterField(
            model_name='mueble',
            name='alumnos_min',
            field=models.IntegerField(verbose_name='Rango minimo de alumnos'),
        ),
        migrations.AlterField(
            model_name='sistemabebedero',
            name='ejecutora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ejecutora', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sistemabebedero',
            name='sistema_de_potabilizacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bebederos.SistemaPotabilizacion'),
        ),
        migrations.AlterField(
            model_name='sistemapotabilizacion',
            name='descripcion',
            field=models.TextField(default='1', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='sistemapotabilizacion',
            name='tipo',
            field=models.CharField(default='1', max_length=15),
        ),
    ]
