# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-27 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0024_auto_20170927_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistemabebedero',
            name='identificador_mb',
            field=models.CharField(max_length=20, verbose_name='Identificador de mueble bebedero'),
        ),
        migrations.AlterField(
            model_name='sistemapotabilizacion',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='sistemapotabilizacion',
            name='tipo',
            field=models.CharField(max_length=15),
        ),
    ]
