# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-27 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0025_auto_20170927_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemabebedero',
            name='linea_ensambjale',
            field=models.CharField(default='1', max_length=5),
        ),
    ]
