# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-28 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0026_sistemabebedero_linea_ensambjale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sistemabebedero',
            old_name='linea_ensambjale',
            new_name='linea_ensamblaje',
        ),
    ]
