# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-28 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0027_auto_20170928_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sistemabebedero',
            name='identificador_mb',
        ),
        migrations.AddField(
            model_name='sistemabebedero',
            name='no_serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='No. Serie'),
        ),
    ]
