# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-29 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0028_auto_20170928_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sistemabebedero',
            old_name='no_serie',
            new_name='identificador',
        ),
    ]
