# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-29 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0029_auto_20170929_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistemabebedero',
            name='identificador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
