# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-03 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0031_remove_sistemabebedero_ejecutora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistemabebedero',
            name='sistema_de_potabilizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sistema_potabilizacion', to='bebederos.SistemaPotabilizacion'),
        ),
    ]
