# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-05 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0035_auto_20171003_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemabebedero',
            name='secuencia_sp',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Secuencia de componentes en el sistema de potabilización'),
        ),
    ]
