# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-05 04:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bebederos', '0036_sistemabebedero_secuencia_sp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemabebedero',
            name='ejecutora',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ejecutora', to=settings.AUTH_USER_MODEL),
        ),
    ]
