# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-05 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0037_sistemabebedero_ejecutora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sistemabebedero',
            name='modulo',
        ),
    ]
