# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-05 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0038_remove_sistemabebedero_modulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sistemabebedero',
            name='secuencia_sp',
        ),
        migrations.AddField(
            model_name='sistemabebedero',
            name='componentes_sp',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Componentes del sistema de potabilización'),
        ),
    ]
