# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-09 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0040_auto_20171005_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='mueble',
            name='total_salidas',
            field=models.IntegerField(default=0),
        ),
    ]
