# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-09 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0042_auto_20171009_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mueble',
            old_name='cantidad_salidas_regulares',
            new_name='cantidad_total_salidas',
        ),
        migrations.RenameField(
            model_name='mueble',
            old_name='total_salidas',
            new_name='salidas_regulares',
        ),
    ]
