# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-09 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0043_auto_20171009_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mueble',
            old_name='cantidad_llenador_de_botellas',
            new_name='llenador_de_botellas',
        ),
        migrations.RenameField(
            model_name='mueble',
            old_name='cantidad_salidas_discapacidad',
            new_name='salidas_discapacidad',
        ),
        migrations.RenameField(
            model_name='mueble',
            old_name='cantidad_total_salidas',
            new_name='total_salidas',
        ),
    ]
