# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-09 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0044_auto_20171009_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mueble',
            old_name='llenador_de_botellas',
            new_name='llenador_botellas',
        ),
    ]
