# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-09 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0045_auto_20171009_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mueble',
            options={'ordering': ['modelo']},
        ),
        migrations.RenameField(
            model_name='mueble',
            old_name='clave',
            new_name='modelo',
        ),
    ]
