# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-10 22:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0046_auto_20171009_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sistemabebedero',
            old_name='sistema_de_potabilizacion',
            new_name='sistema_potabilizacion',
        ),
    ]
