# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-12 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0047_auto_20171010_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sistemabebedero',
            name='identificador',
        ),
        migrations.AddField(
            model_name='sistemabebedero',
            name='no_trazabilidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sistemapotabilizacion',
            name='litros_vida',
            field=models.IntegerField(verbose_name='Litrso de vida'),
        ),
    ]
