# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-14 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0048_auto_20171012_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemabebedero',
            name='asignacion',
            field=models.BooleanField(default=False),
        ),
    ]
