# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-14 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0049_sistemabebedero_asignacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistemabebedero',
            name='asignacion',
            field=models.BooleanField(default=False, verbose_name='Si ya se descargó. imprimió y asignó la guia de trazabilidad al mueble correspondiente, oprima el botón'),
        ),
    ]
