# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-18 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0050_auto_20171014_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sistemabebedero',
            name='componentes_sp',
        ),
        migrations.AddField(
            model_name='sistemabebedero',
            name='etapas_sp',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Etapas del sistema de potabilización'),
        ),
    ]
