# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-20 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0051_auto_20171018_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemabebedero',
            name='capacidad_tanque_presurizador',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
