# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-27 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0052_sistemabebedero_capacidad_tanque_presurizador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistemabebedero',
            name='linea_ensamblaje',
            field=models.CharField(blank=True, choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8)], max_length=5, null=True),
        ),
    ]
