# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-30 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0053_auto_20171027_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistemabebedero',
            name='etapas_sp',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Etapas del sistema potabilizador'),
        ),
        migrations.AlterField(
            model_name='sistemabebedero',
            name='identificador_sp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Identificador del sistema potabilizador (No. de serie)'),
        ),
        migrations.AlterField(
            model_name='sistemabebedero',
            name='linea_ensamblaje',
            field=models.CharField(blank=True, choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8)], max_length=5, null=True, verbose_name='Línea de ensamblaje'),
        ),
        migrations.AlterField(
            model_name='sistemabebedero',
            name='sistema_potabilizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sistema_potabilizacion', to='bebederos.SistemaPotabilizacion', verbose_name='Sistema potabilizador'),
        ),
    ]
