# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-05 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0054_auto_20171029_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sistemabebedero',
            old_name='identificador_sp',
            new_name='no_serie_sp',
        ),
        migrations.RemoveField(
            model_name='sistemapotabilizacion',
            name='litros_vida',
        ),
        migrations.AlterField(
            model_name='sistemabebedero',
            name='etapas_sp',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
