# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-06 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0056_remove_sistemabebedero_ejecutora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistemabebedero',
            name='etapas_sp',
            field=models.CharField(blank=True, choices=[('A1', 'Enero'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3')], max_length=15, null=True),
        ),
    ]
