# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-06 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0057_auto_20171105_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistemabebedero',
            name='etapas_sp',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3')], max_length=15, null=True, verbose_name='Etapas del sistema potabilizador'),
        ),
        migrations.AlterField(
            model_name='sistemabebedero',
            name='no_serie_sp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='No. de serie del sistema potabilizador '),
        ),
    ]
