# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-08 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0058_auto_20171106_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistemabebedero',
            name='etapas_sp',
            field=models.CharField(blank=True, choices=[('Alumina', 'Alumina'), ('Carbon Activado', 'Carbon Activado'), ('Ambos', 'Ambos')], max_length=20, null=True, verbose_name='Etapas del sistema potabilizador'),
        ),
    ]
