# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-27 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0059_auto_20171108_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sistemabebedero',
            name='etapas_sp',
        ),
        migrations.RemoveField(
            model_name='sistemapotabilizacion',
            name='descripcion',
        ),
    ]
