# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-17 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0061_auto_20180417_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sistemabebedero',
            name='linea_ensamblaje',
        ),
    ]
