# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-17 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0062_remove_sistemabebedero_linea_ensamblaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistemabebedero',
            name='proveedor',
            field=models.CharField(choices=[('CRG', 'CRG'), ('KEVANCY', 'KEVANCY'), ('TAMA', 'TAMA')], default='CRG', max_length=10),
        ),
    ]
