# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-18 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0063_auto_20180417_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemabebedero',
            name='status',
            field=models.CharField(choices=[('En proceso', 'En proceso'), ('Terminado', 'Terminado')], default='En proceso', max_length=10),
        ),
    ]
