# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-18 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0064_sistemabebedero_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistemabebedero',
            name='no_serie_mueble',
            field=models.IntegerField(blank=True, null=True, verbose_name='No. de serie de mueble'),
        ),
    ]
