# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-30 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0066_remove_sistemabebedero_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemabebedero',
            name='packing_list',
            field=models.BooleanField(default=False, verbose_name='Si el mueble ya salio del taller, oprima aquí'),
        ),
    ]
