# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0002_auto_20170727_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='primerprueba',
            options={'ordering': ['escuela'], 'verbose_name_plural': 'Primeras pruebas'},
        ),
        migrations.AlterModelOptions(
            name='segundaprueba',
            options={'ordering': ['escuela'], 'verbose_name_plural': 'Segundas pruebas'},
        ),
    ]
