# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-04 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0004_auto_20170728_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='primerprueba',
            name='aprobacion_interna',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
