# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-07 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0005_primerprueba_aprobacion_interna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primerprueba',
            name='aprobacion_interna',
            field=models.CharField(choices=[('En espera', 'En espera'), ('No aprobado', 'No aprobado'), ('Aprobado', 'Aprobado')], default=0, max_length=11),
        ),
    ]
