# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-08 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0006_auto_20170807_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='primerprueba',
            old_name='aprobacion_interna',
            new_name='aprobacion',
        ),
    ]
