# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-08 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0007_auto_20170808_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primerprueba',
            name='aprobacion',
            field=models.CharField(choices=[('En espera', 'En espera'), ('No aprobado', 'No aprobado'), ('Aprobado', 'Aprobado')], default='En espera', max_length=11),
        ),
    ]
