# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-10 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0009_segundaprueba_aprobacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primerprueba',
            name='aprobacion',
            field=models.CharField(choices=[('En espera', 'En espera'), ('Aprobado', 'Aprobado'), ('No aprobado', 'No aprobado')], default='En espera', max_length=11, verbose_name='Aprobación'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='aprobacion',
            field=models.CharField(choices=[('En espera', 'En espera'), ('Aprobado', 'Aprobado'), ('No aprobado', 'No aprobado')], default='En espera', max_length=11, verbose_name='Aprobación'),
        ),
    ]
