# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0010_auto_20170810_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='primerprueba',
            name='dictamen_sistema_potabilizador',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/1/resultados/%Y/%m/%d/', verbose_name='Dictamen del sistema potabilizador a utilizar'),
        ),
        migrations.AddField(
            model_name='primerprueba',
            name='dictamen_validacion',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/2/validacion/%Y/%m/%d/', verbose_name='Dictamen de validación'),
        ),
        migrations.AddField(
            model_name='primerprueba',
            name='reporte_toma_agua',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/2/reporte_de_toma/%Y/%m/%d/', verbose_name='Reporte de toma de muestra'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='resultados',
            field=models.FileField(upload_to='pruebas/1/resultados/%Y/%m/%d/', verbose_name='Resultados de muestreo'),
        ),
    ]
