# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-31 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0012_auto_20170811_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segundaprueba',
            name='dictamen_sistema_potabilizador',
        ),
    ]
