# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-29 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0015_auto_20170927_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primerprueba',
            name='resultados_inifed',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/1/resultados/%Y/%m/%d/', verbose_name='Resultados de análisis para INIFED'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='resultados_laboratorio',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/1/resultados/%Y/%m/%d/', verbose_name='Resultados de análisis de laboratorio'),
        ),
    ]
