# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-30 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0016_auto_20170929_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segundaprueba',
            name='constancia_recepcion',
        ),
        migrations.RemoveField(
            model_name='segundaprueba',
            name='resultados',
        ),
        migrations.AddField(
            model_name='primerprueba',
            name='acta_primer_prueba',
            field=models.FileField(default='default.pdf', upload_to='pruebas/2/acta_de_segunda_prueba/%Y/%m/%d/', verbose_name='Acta de segunda prueba'),
        ),
        migrations.AddField(
            model_name='segundaprueba',
            name='resultados_inifed',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/1/resultados/%Y/%m/%d/', verbose_name='Resultados de análisis para INIFED'),
        ),
        migrations.AddField(
            model_name='segundaprueba',
            name='resultados_laboratorio',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/1/resultados/%Y/%m/%d/', verbose_name='Resultados de análisis de laboratorio'),
        ),
        migrations.AddField(
            model_name='segundaprueba',
            name='sugerencias_sp',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/1/resultados/%Y/%m/%d/', verbose_name='Sugerencia de Sistema Potabilizador'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='reporte_toma_agua',
            field=models.FileField(default='default.pdf', upload_to='pruebas/1/reporte_de_toma/%Y/%m/%d/', verbose_name='Reporte de toma de muestra'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='acta_segunda_prueba',
            field=models.FileField(default='default.pdf', upload_to='pruebas/2/acta_de_segunda_prueba/%Y/%m/%d/', verbose_name='Acta de segunda prueba'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='dictamen_validacion',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/1/resultados/%Y/%m/%d/', verbose_name='Dictamen de validación'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='reporte_toma_agua',
            field=models.FileField(default='default.pdf', upload_to='pruebas/2/reporte_de_toma/%Y/%m/%d/', verbose_name='Reporte de toma de muestra'),
        ),
    ]
