# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-30 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0017_auto_20170930_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primerprueba',
            name='acta_primer_prueba',
            field=models.FileField(upload_to='pruebas/2/acta_de_segunda_prueba/%Y/%m/%d/', verbose_name='Acta de segunda prueba'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='reporte_toma_agua',
            field=models.FileField(upload_to='pruebas/1/reporte_de_toma/%Y/%m/%d/', verbose_name='Reporte de toma de muestra'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='acta_segunda_prueba',
            field=models.FileField(upload_to='pruebas/2/acta_de_segunda_prueba/%Y/%m/%d/', verbose_name='Acta de segunda prueba'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='reporte_toma_agua',
            field=models.FileField(upload_to='pruebas/2/reporte_de_toma/%Y/%m/%d/', verbose_name='Reporte de toma de muestra'),
        ),
    ]
