# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-30 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0018_auto_20170930_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primerprueba',
            name='acta_primer_prueba',
            field=models.FileField(upload_to='pruebas/2/acta_de_segunda_prueba/%Y/%m/%d/', verbose_name='Acta de primer prueba de calidad de agua'),
        ),
    ]
