# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-30 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0020_auto_20170930_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segundaprueba',
            name='acta_segunda_prueba',
            field=models.FileField(upload_to='pruebas/2/acta_de_segunda_prueba/%Y/%m/%d/', verbose_name='Acta de segunda prueba de calidad de agua'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='aprobacion_interna',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/1/resultados/%Y/%m/%d/', verbose_name='Aprobación interna'),
        ),
    ]
