# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-30 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0021_auto_20170930_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segundaprueba',
            name='aprobacion_interna',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/2/resultados/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='dictamen_validacion',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/2/resultados/%Y/%m/%d/', verbose_name='Dictamen de validación'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='resultados_inifed',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/2/resultados/%Y/%m/%d/', verbose_name='Resultados de análisis para INIFED'),
        ),
    ]
