# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-30 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0022_auto_20170930_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segundaprueba',
            name='resultados_laboratorio',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/2/resultados/%Y/%m/%d/', verbose_name='Resultados de análisis de laboratorio'),
        ),
    ]
