# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-02 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0023_auto_20170930_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='primerprueba',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/1/fotos/%Y/%m/%d/', verbose_name='Evidencia fotografica de recepción de muestra'),
        ),
    ]
