# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-04 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0025_segundaprueba_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primerprueba',
            name='acta_primer_prueba',
        ),
        migrations.RemoveField(
            model_name='primerprueba',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='primerprueba',
            name='resultados_inifed',
        ),
        migrations.RemoveField(
            model_name='primerprueba',
            name='sugerencias_sp',
        ),
        migrations.RemoveField(
            model_name='primerprueba',
            name='video',
        ),
        migrations.AddField(
            model_name='primerprueba',
            name='foto_recepcion',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/1/fotos/%Y/%m/%d/', verbose_name='Evidencia fotográfica de recepción de muestra'),
        ),
        migrations.AddField(
            model_name='primerprueba',
            name='foto_toma_agua',
            field=models.FileField(default='default.pdf', upload_to='pruebas/1/fotos/%Y/%m/%d/', verbose_name='Evidencia fotográfica de toma de agua'),
        ),
        migrations.AddField(
            model_name='primerprueba',
            name='resultados_IMTA',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/1/resultados/%Y/%m/%d/', verbose_name='Resultados de análisis con propuesta de sistema potabilizador para visto bueno de IMTA'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='dictamen_sistema_potabilizador',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/1/dictamen/%Y/%m/%d/', verbose_name='Dictamen del sistema potabilizador a utilizar'),
        ),
    ]
