# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-04 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0026_auto_20171004_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primerprueba',
            name='foto_toma_agua',
            field=models.FileField(upload_to='pruebas/1/fotos/%Y/%m/%d/', verbose_name='Evidencia fotográfica de toma de agua'),
        ),
    ]
