# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-04 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0027_auto_20171004_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segundaprueba',
            old_name='foto',
            new_name='foto_recepcion',
        ),
        migrations.RenameField(
            model_name='segundaprueba',
            old_name='resultados_inifed',
            new_name='resultados_IMTA',
        ),
        migrations.RemoveField(
            model_name='segundaprueba',
            name='acta_segunda_prueba',
        ),
        migrations.RemoveField(
            model_name='segundaprueba',
            name='video',
        ),
        migrations.AddField(
            model_name='segundaprueba',
            name='foto_toma_agua',
            field=models.FileField(default='default.pdf', upload_to='pruebas/2/video/%Y/%m/%d/', verbose_name='Evidencia fotográfica de toma de agua'),
        ),
    ]
