# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-04 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0028_auto_20171004_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segundaprueba',
            name='foto_toma_agua',
            field=models.FileField(upload_to='pruebas/2/video/%Y/%m/%d/', verbose_name='Evidencia fotográfica de toma de agua'),
        ),
    ]
