# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-04 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0029_auto_20171004_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segundaprueba',
            name='aprobacion_interna',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/2/resultados/%Y/%m/%d/', verbose_name='Aprobación interna'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='resultados_IMTA',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/2/resultados/%Y/%m/%d/', verbose_name='Resultados de análisis para IMTA'),
        ),
    ]
