# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-05 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0032_auto_20171005_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primerprueba',
            name='arsenico',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Arsénico'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='coliformes_fecales',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Coliformes fecales (unidades)'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='coliformes_totales',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Coliformes totales (Unidades)'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='color_verdadero',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Color verdadero (U Pt-Co)'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='conductividad_electrica',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Conductividad eléctrica (µS/cm)'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='dureza_total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Dureza total (CaCO3)'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='floururos',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Fluoruros'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='hierro',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Hierro'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='manganesio',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Manganeso'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='nitratos',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Nitratos'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='ph',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='pH (unidades de pH)'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='plomo',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Plomo'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='solidos_disueltos',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Sólidos disueltos totales'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='sulfatos',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Sulfatos'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='turbiedad',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Turbiedad (UTN o equivalente)'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='arsenico',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Arsénico'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='coliformes_fecales',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Coliformes fecales (unidades)'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='coliformes_totales',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Coliformes totales (Unidades)'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='color_verdadero',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Color verdadero (U Pt-Co)'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='conductividad_electrica',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Conductividad eléctrica (µS/cm)'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='dureza_total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Dureza total (CaCO3)'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='floururos',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Fluoruros'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='hierro',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Hierro'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='manganesio',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Manganeso'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='nitratos',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Nitratos'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='ph',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='pH (unidades de pH)'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='plomo',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Plomo'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='solidos_disueltos',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Sólidos disueltos totales'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='sulfatos',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Sulfatos'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='turbiedad',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Turbiedad (UTN o equivalente)'),
        ),
    ]
