# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-06 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0033_auto_20171005_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='primerprueba',
            name='no_registro',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número de registro'),
        ),
        migrations.AddField(
            model_name='segundaprueba',
            name='no_registro',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número de registro'),
        ),
    ]
