# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-08 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0034_auto_20171006_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primerprueba',
            name='resultados_IMTA',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/1/resultados/%Y/%m/%d/', verbose_name='Resultados de análisis con propuesta de sistema potabilizador'),
        ),
    ]
