# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-09 17:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0035_auto_20171008_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primerprueba',
            name='escuela',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escuela_primer_prueba', to=settings.AUTH_USER_MODEL),
        ),
    ]
