# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-09 18:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0036_auto_20171009_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primerprueba',
            name='creacion',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 9, 18, 2, 39, 789562, tzinfo=utc), verbose_name='Fecha de creación'),
        ),
    ]
