# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-09 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0037_auto_20171009_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primerprueba',
            name='creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
    ]
