# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-09 21:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0039_auto_20171009_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primerprueba',
            name='creacion',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 9, 21, 3, 58, 79430, tzinfo=utc), verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='creacion',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 9, 21, 3, 58, 80739, tzinfo=utc), verbose_name='Fecha de creación'),
        ),
    ]
