# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-09 21:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0041_auto_20171009_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primerprueba',
            name='creacion',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 9, 21, 28, 53, 567522, tzinfo=utc), verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='creacion',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 9, 21, 28, 53, 568803, tzinfo=utc), verbose_name='Fecha de creación'),
        ),
    ]
