# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-09 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0042_auto_20171009_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primerprueba',
            name='creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
    ]
