# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-09 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0043_auto_20171009_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='primerprueba',
            name='creacion_reporte_analisis',
            field=models.DateField(null=True, verbose_name='Fecha de creación del reporte de análisis'),
        ),
    ]
