# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-09 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0044_primerprueba_creacion_reporte_analisis'),
    ]

    operations = [
        migrations.AddField(
            model_name='segundaprueba',
            name='creacion_reporte_analisis',
            field=models.DateField(null=True, verbose_name='Fecha de creación del reporte de análisis'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='creacion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
    ]
