# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-10 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0046_auto_20171009_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='primerprueba',
            old_name='manganesio',
            new_name='manganeso',
        ),
        migrations.RenameField(
            model_name='segundaprueba',
            old_name='manganesio',
            new_name='manganeso',
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='creacion_reporte_analisis',
            field=models.DateField(null=True, verbose_name='Fecha del reporte de análisis'),
        ),
    ]
