# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-11 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0048_auto_20171011_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primerprueba',
            name='creacion_reporte_analisis',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del reporte de análisis'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='no_registro',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número de registro (Orden de Trabajo)'),
        ),
    ]
