# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-11 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0049_auto_20171011_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primerprueba',
            name='hierro',
            field=models.FloatField(blank=True, null=True, verbose_name='Hierro'),
        ),
    ]
