# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-11 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0050_auto_20171011_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primerprueba',
            name='manganeso',
            field=models.FloatField(blank=True, null=True, verbose_name='Manganeso'),
        ),
    ]
