# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-11 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0051_auto_20171011_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primerprueba',
            name='arsenico',
            field=models.FloatField(blank=True, null=True, verbose_name='Arsénico'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='coliformes_fecales',
            field=models.FloatField(blank=True, null=True, verbose_name='Coliformes fecales (unidades)'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='coliformes_totales',
            field=models.FloatField(blank=True, null=True, verbose_name='Coliformes totales (Unidades)'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='color_verdadero',
            field=models.FloatField(blank=True, null=True, verbose_name='Color verdadero (U Pt-Co)'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='dureza_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Dureza total (CaCO3)'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='floururos',
            field=models.FloatField(blank=True, null=True, verbose_name='Fluoruros'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='nitratos',
            field=models.FloatField(blank=True, null=True, verbose_name='Nitratos'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='ph',
            field=models.FloatField(blank=True, null=True, verbose_name='pH (unidades de pH)'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='plomo',
            field=models.FloatField(blank=True, null=True, verbose_name='Plomo'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='solidos_disueltos',
            field=models.FloatField(blank=True, null=True, verbose_name='Sólidos disueltos totales'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='sulfatos',
            field=models.FloatField(blank=True, null=True, verbose_name='Sulfatos'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='turbiedad',
            field=models.FloatField(blank=True, null=True, verbose_name='Turbiedad (UTN o equivalente)'),
        ),
    ]
