# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-14 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0052_auto_20171011_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segundaprueba',
            name='foto_recepcion',
        ),
        migrations.AddField(
            model_name='segundaprueba',
            name='cadena_custodia',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/1/cadena_custioda/%Y/%m/%d/', verbose_name='Cadena de custodia'),
        ),
        migrations.AddField(
            model_name='segundaprueba',
            name='hoja_campo',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/1/hoja_campo/%Y/%m/%d/', verbose_name='Hoja de campo'),
        ),
    ]
