# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-16 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0053_auto_20171014_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segundaprueba',
            name='aprobacion',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('No aprobado', 'No aprobado')], default='En espera', max_length=11, verbose_name='Aprobación'),
        ),
    ]
