# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-16 16:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0054_auto_20171016_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primerprueba',
            name='ph',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MinValueValidator(14)], verbose_name='pH (unidades de pH)'),
        ),
    ]
