# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-17 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0055_auto_20171016_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primerprueba',
            name='ph',
            field=models.FloatField(blank=True, null=True, verbose_name='pH (unidades de pH)'),
        ),
    ]
