# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-19 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0056_auto_20171017_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segundaprueba',
            name='arsenico',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Arsénico (mg/L)'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='coliformes_fecales',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Coliformes fecales (UFC)'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='coliformes_totales',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Coliformes totales (UFC)'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='hierro',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Hierro (mg/L)'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='manganeso',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Manganeso (mg/L)'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='plomo',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Plomo (mg/L)'),
        ),
    ]
