# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-19 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0057_auto_20171019_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primerprueba',
            name='arsenico',
            field=models.FloatField(blank=True, null=True, verbose_name='Arsénico (mg/L)'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='coliformes_fecales',
            field=models.FloatField(blank=True, null=True, verbose_name='Coliformes fecales (UFC)'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='coliformes_totales',
            field=models.FloatField(blank=True, null=True, verbose_name='Coliformes totales (UFC)'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='dureza_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Dureza total (CaCO3) (mg/L)'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='floururos',
            field=models.FloatField(blank=True, null=True, verbose_name='Fluoruros (mg/L)'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='hierro',
            field=models.FloatField(blank=True, null=True, verbose_name='Hierro (mg/L)'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='manganeso',
            field=models.FloatField(blank=True, null=True, verbose_name='Manganeso (mg/L)'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='nitratos',
            field=models.FloatField(blank=True, null=True, verbose_name='Nitratos (mg/L)'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='plomo',
            field=models.FloatField(blank=True, null=True, verbose_name='Plomo (mg/L)'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='solidos_disueltos',
            field=models.FloatField(blank=True, null=True, verbose_name='Sólidos disueltos totales (mg/L)'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='sulfatos',
            field=models.FloatField(blank=True, null=True, verbose_name='Sulfatos (mg/L)'),
        ),
    ]
