# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-19 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0058_auto_20171019_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primerprueba',
            name='resultados_IMTA',
        ),
        migrations.AddField(
            model_name='primerprueba',
            name='propuesta_sistema_potabilizador',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/1/resultados/%Y/%m/%d/', verbose_name='Propuesta de sistema potabilizador'),
        ),
    ]
