# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-20 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0060_auto_20171019_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segundaprueba',
            name='dureza_total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Dureza total (CaCO3) (mg/L)'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='floururos',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Fluoruros (mg/L)'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='nitratos',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Nitratos (mg/L)'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='solidos_disueltos',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Sólidos disueltos totales (mg/L)'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='sulfatos',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Sulfatos (mg/L)'),
        ),
    ]
