# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-20 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0061_auto_20171020_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segundaprueba',
            name='aprobacion_interna',
        ),
    ]
