# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-20 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0062_remove_segundaprueba_aprobacion_interna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segundaprueba',
            name='resultados_IMTA',
        ),
    ]
