# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-20 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0063_remove_segundaprueba_resultados_imta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segundaprueba',
            name='hoja_campo',
        ),
        migrations.AddField(
            model_name='segundaprueba',
            name='registro_campo',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/1/hoja_campo/%Y/%m/%d/', verbose_name='Registro de campo'),
        ),
    ]
