# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-28 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0064_auto_20171020_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primerprueba',
            name='cadena_custodia',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/1/cadenasCustioda/%Y/%m/%d/', verbose_name='Cadena de custodia'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='dictamen_sistema_potabilizador',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/1/dictamenes/%Y/%m/%d/', verbose_name='Dictamen del sistema potabilizador a utilizar'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='registro_campo',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/1/hojasCampo/%Y/%m/%d/', verbose_name='Registro de campo'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='reporte_toma_agua',
            field=models.FileField(upload_to='pruebas/1/reportes/%Y/%m/%d/', verbose_name='Reporte de toma de muestra'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='cadena_custodia',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/1/cadenasCustioda/%Y/%m/%d/', verbose_name='Cadena de custodia'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='dictamen_validacion',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/2/dictamenes/%Y/%m/%d/', verbose_name='Dictamen de validación'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='foto_toma_agua',
            field=models.FileField(upload_to='pruebas/2/fotos/%Y/%m/%d/', verbose_name='Evidencia fotográfica de toma de agua'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='registro_campo',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/1/hojasCampo/%Y/%m/%d/', verbose_name='Registro de campo'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='reporte_toma_agua',
            field=models.FileField(upload_to='pruebas/2/reportes_de_toma/%Y/%m/%d/', verbose_name='Reporte de toma de muestra'),
        ),
    ]
