# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-02 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0066_auto_20171030_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primerprueba',
            name='aprobacion',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('No aprobado', 'No aprobado'), ('En espera', 'En espera')], default='En espera', max_length=11, verbose_name='Aprobación'),
        ),
    ]
