# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-06 02:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0067_auto_20171102_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segundaprueba',
            name='laboratorio',
        ),
    ]
