# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-06 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0070_auto_20171105_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primerprueba',
            name='no_registro',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de registro (Orden de Trabajo)'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='no_registro',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de registro'),
        ),
    ]
