# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-06 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0071_auto_20171106_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primerprueba',
            name='laboratorio',
        ),
        migrations.AddField(
            model_name='primerprueba',
            name='comparacion_arsenico',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1),
        ),
        migrations.AddField(
            model_name='primerprueba',
            name='comparacion_coliformes_fecales',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1),
        ),
        migrations.AddField(
            model_name='primerprueba',
            name='comparacion_coliformes_totales',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1),
        ),
        migrations.AddField(
            model_name='primerprueba',
            name='comparacion_color_verdadero',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1),
        ),
        migrations.AddField(
            model_name='primerprueba',
            name='comparacion_conductividad_electrica',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1),
        ),
        migrations.AddField(
            model_name='primerprueba',
            name='comparacion_dureza_total',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1),
        ),
        migrations.AddField(
            model_name='primerprueba',
            name='comparacion_floururos',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1),
        ),
        migrations.AddField(
            model_name='primerprueba',
            name='comparacion_hierro',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1),
        ),
        migrations.AddField(
            model_name='primerprueba',
            name='comparacion_manganeso',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1),
        ),
        migrations.AddField(
            model_name='primerprueba',
            name='comparacion_nitratos',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1),
        ),
        migrations.AddField(
            model_name='primerprueba',
            name='comparacion_ph',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1),
        ),
        migrations.AddField(
            model_name='primerprueba',
            name='comparacion_plomo',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1),
        ),
        migrations.AddField(
            model_name='primerprueba',
            name='comparacion_solidos_disueltos',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1),
        ),
        migrations.AddField(
            model_name='primerprueba',
            name='comparacion_sulfatos',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1),
        ),
        migrations.AddField(
            model_name='primerprueba',
            name='comparacion_turbiedad',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='coliformes_fecales',
            field=models.FloatField(blank=True, null=True, verbose_name='Coliformes fecales (UFC o NMP)'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='coliformes_totales',
            field=models.FloatField(blank=True, null=True, verbose_name='Coliformes totales (UFC o NMP)'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='coliformes_fecales',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Coliformes fecales (UFC o NMP)'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='coliformes_totales',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Coliformes totales (UFC o NMP)'),
        ),
    ]
