# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-06 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0072_auto_20171106_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primerprueba',
            name='foto_toma_agua',
        ),
        migrations.AddField(
            model_name='primerprueba',
            name='foto_toma_agua_1',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/1/fotos/%Y/%m/%d/', verbose_name='Fotografía 1'),
        ),
        migrations.AddField(
            model_name='primerprueba',
            name='foto_toma_agua_2',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/1/fotos/%Y/%m/%d/', verbose_name='Fotografía 2'),
        ),
        migrations.AddField(
            model_name='primerprueba',
            name='video_toma_agua',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/1/fotos/%Y/%m/%d/', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='comparacion_arsenico',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='comparacion_coliformes_fecales',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='comparacion_coliformes_totales',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='comparacion_color_verdadero',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='comparacion_conductividad_electrica',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='comparacion_dureza_total',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='comparacion_floururos',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='comparacion_hierro',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='comparacion_manganeso',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='comparacion_nitratos',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='comparacion_ph',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='comparacion_plomo',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='comparacion_solidos_disueltos',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='comparacion_sulfatos',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.'),
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='comparacion_turbiedad',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.'),
        ),
    ]
