# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-06 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0073_auto_20171106_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='segundaprueba',
            name='comparacion_arsenico',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.'),
        ),
        migrations.AddField(
            model_name='segundaprueba',
            name='comparacion_coliformes_fecales',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.'),
        ),
        migrations.AddField(
            model_name='segundaprueba',
            name='comparacion_coliformes_totales',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.'),
        ),
        migrations.AddField(
            model_name='segundaprueba',
            name='comparacion_color_verdadero',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.'),
        ),
        migrations.AddField(
            model_name='segundaprueba',
            name='comparacion_conductividad_electrica',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.'),
        ),
        migrations.AddField(
            model_name='segundaprueba',
            name='comparacion_dureza_total',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.'),
        ),
        migrations.AddField(
            model_name='segundaprueba',
            name='comparacion_floururos',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.'),
        ),
        migrations.AddField(
            model_name='segundaprueba',
            name='comparacion_hierro',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.'),
        ),
        migrations.AddField(
            model_name='segundaprueba',
            name='comparacion_manganeso',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.'),
        ),
        migrations.AddField(
            model_name='segundaprueba',
            name='comparacion_nitratos',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.'),
        ),
        migrations.AddField(
            model_name='segundaprueba',
            name='comparacion_ph',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.'),
        ),
        migrations.AddField(
            model_name='segundaprueba',
            name='comparacion_plomo',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.'),
        ),
        migrations.AddField(
            model_name='segundaprueba',
            name='comparacion_solidos_disueltos',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.'),
        ),
        migrations.AddField(
            model_name='segundaprueba',
            name='comparacion_sulfatos',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.'),
        ),
        migrations.AddField(
            model_name='segundaprueba',
            name='comparacion_turbiedad',
            field=models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.'),
        ),
    ]
