# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-07 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0074_auto_20171106_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segundaprueba',
            name='foto_toma_agua',
        ),
        migrations.AddField(
            model_name='segundaprueba',
            name='foto_toma_agua_1',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/1/fotos/%Y/%m/%d/', verbose_name='Fotografía 1'),
        ),
        migrations.AddField(
            model_name='segundaprueba',
            name='foto_toma_agua_2',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/1/fotos/%Y/%m/%d/', verbose_name='Fotografía 2'),
        ),
        migrations.AddField(
            model_name='segundaprueba',
            name='video_toma_agua',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/1/fotos/%Y/%m/%d/', verbose_name='Video'),
        ),
    ]
