# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-07 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0075_auto_20171106_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primerprueba',
            name='conductividad_electrica',
            field=models.FloatField(blank=True, null=True, verbose_name='Conductividad eléctrica (µS/cm)'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='arsenico',
            field=models.FloatField(blank=True, null=True, verbose_name='Arsénico (mg/L)'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='coliformes_fecales',
            field=models.FloatField(blank=True, null=True, verbose_name='Coliformes fecales (UFC o NMP)'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='coliformes_totales',
            field=models.FloatField(blank=True, null=True, verbose_name='Coliformes totales (UFC o NMP)'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='color_verdadero',
            field=models.FloatField(blank=True, null=True, verbose_name='Color verdadero (U Pt-Co)'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='conductividad_electrica',
            field=models.FloatField(blank=True, null=True, verbose_name='Conductividad eléctrica (µS/cm)'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='dureza_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Dureza total (CaCO3) (mg/L)'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='floururos',
            field=models.FloatField(blank=True, null=True, verbose_name='Fluoruros (mg/L)'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='hierro',
            field=models.FloatField(blank=True, null=True, verbose_name='Hierro (mg/L)'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='manganeso',
            field=models.FloatField(blank=True, null=True, verbose_name='Manganeso (mg/L)'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='nitratos',
            field=models.FloatField(blank=True, null=True, verbose_name='Nitratos (mg/L)'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='ph',
            field=models.FloatField(blank=True, null=True, verbose_name='pH (unidades de pH)'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='plomo',
            field=models.FloatField(blank=True, null=True, verbose_name='Plomo (mg/L)'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='solidos_disueltos',
            field=models.FloatField(blank=True, null=True, verbose_name='Sólidos disueltos totales (mg/L)'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='sulfatos',
            field=models.FloatField(blank=True, null=True, verbose_name='Sulfatos (mg/L)'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='turbiedad',
            field=models.FloatField(blank=True, null=True, verbose_name='Turbiedad (UTN o equivalente)'),
        ),
    ]
