# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-27 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0076_auto_20171107_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primerprueba',
            name='aprobacion',
        ),
        migrations.RemoveField(
            model_name='primerprueba',
            name='dictamen_sistema_potabilizador',
        ),
        migrations.AddField(
            model_name='primerprueba',
            name='validacion',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('No aprobado', 'No aprobado'), ('En espera', 'En espera')], default='En espera', max_length=11, verbose_name='Validación'),
        ),
    ]
