# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-27 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0077_auto_20171127_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primerprueba',
            name='validacion',
            field=models.CharField(blank=True, choices=[('Validado', 'Validado'), ('No validado', 'No validado')], max_length=11, null=True, verbose_name='Validación'),
        ),
    ]
