# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-27 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0078_auto_20171127_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primerprueba',
            name='propuesta_sistema_potabilizador',
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='validacion',
            field=models.CharField(choices=[('Validado', 'Validado'), ('No validado', 'No validado')], default='En espera', max_length=11, verbose_name='Validación'),
        ),
    ]
