# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-30 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0081_auto_20171129_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segundaprueba',
            name='validacion',
            field=models.CharField(choices=[('Validado', 'Validado'), ('No validado', 'No validado'), ('En espera', 'En espera')], default='En espera', max_length=11, verbose_name='Validación'),
        ),
    ]
