# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-01 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0082_auto_20171130_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primerprueba',
            name='video_toma_agua',
        ),
        migrations.RemoveField(
            model_name='segundaprueba',
            name='video_toma_agua',
        ),
        migrations.AlterField(
            model_name='primerprueba',
            name='reporte_toma_agua',
            field=models.FileField(upload_to='pruebas/1/reportes/%Y/%m/%d/', verbose_name='Etiqueta de muestra'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='reporte_toma_agua',
            field=models.FileField(upload_to='pruebas/2/reportes_de_toma/%Y/%m/%d/', verbose_name='Etiqueta de muestra'),
        ),
    ]
