# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-22 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0086_auto_20180122_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primerprueba',
            name='foto_toma_agua_1',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/1/fotos/%Y/%m/%d/', verbose_name='Fotografía de fachada de la escuela donde se muestre el CCT'),
        ),
    ]
