# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-13 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0089_auto_20180312_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primerprueba',
            name='rastreabilidad_interna_envio',
        ),
        migrations.RemoveField(
            model_name='primerprueba',
            name='rastreabilidad_interna_recepcion',
        ),
        migrations.RemoveField(
            model_name='segundaprueba',
            name='rastreabilidad_interna_envio',
        ),
        migrations.RemoveField(
            model_name='segundaprueba',
            name='rastreabilidad_interna_recepcion',
        ),
    ]
