# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-30 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0090_auto_20180313_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primerprueba',
            name='empresa_envio',
        ),
        migrations.RemoveField(
            model_name='primerprueba',
            name='modalidad_envio',
        ),
        migrations.RemoveField(
            model_name='primerprueba',
            name='no_rastreabilidad',
        ),
        migrations.RemoveField(
            model_name='segundaprueba',
            name='empresa_envio',
        ),
        migrations.RemoveField(
            model_name='segundaprueba',
            name='modalidad_envio',
        ),
        migrations.RemoveField(
            model_name='segundaprueba',
            name='no_rastreabilidad',
        ),
    ]
