# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-23 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0093_auto_20180522_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primerprueba',
            name='creacion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de muestreo'),
        ),
    ]
