# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-05 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0094_auto_20180523_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primerprueba',
            name='reporte_toma_agua',
        ),
        migrations.AddField(
            model_name='primerprueba',
            name='foto_toma_agua_3',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/1/reportes/%Y/%m/%d/', verbose_name='Total de muestras'),
        ),
    ]
