# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-05 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0095_auto_20180605_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primerprueba',
            name='foto_toma_agua_3',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/1/fotos/%Y/%m/%d/', verbose_name='Total de muestras'),
        ),
    ]
