# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-05 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0096_auto_20180605_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='segundaprueba',
            name='foto_toma_agua_3',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/2/fotos/%Y/%m/%d/', verbose_name='Total de muestras'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='cadena_custodia',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/2/cadenasCustioda/%Y/%m/%d/', verbose_name='Cadena de custodia'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='foto_toma_agua_1',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/2/fotos/%Y/%m/%d/', verbose_name='Fotografía de fachada de la escuela donde se muestre el CCT'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='foto_toma_agua_2',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/2/fotos/%Y/%m/%d/', verbose_name='Fotografía de muestra en el punto de muestro'),
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='registro_campo',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/2/hojasCampo/%Y/%m/%d/', verbose_name='Registro de campo'),
        ),
    ]
