# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-05 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0097_auto_20180605_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segundaprueba',
            name='creacion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de muestreo'),
        ),
    ]
