# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-29 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0099_remove_segundaprueba_reporte_toma_agua'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segundaprueba',
            name='foto_toma_agua_2',
        ),
        migrations.RemoveField(
            model_name='segundaprueba',
            name='foto_toma_agua_3',
        ),
        migrations.AlterField(
            model_name='segundaprueba',
            name='foto_toma_agua_1',
            field=models.FileField(blank=True, null=True, upload_to='pruebas/2/fotos/%Y/%m/%d/', verbose_name='Etiqueta de muestra'),
        ),
    ]
