# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-05 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasAgua', '0100_auto_20180629_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segundaprueba',
            name='creacion_reporte_analisis',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de creación del reporte de análisis'),
        ),
    ]
