# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 17:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'En espera'), (2, 'En proceso de solución'), (3, 'Solucionado')], default=1)),
                ('prioridad', models.IntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta')])),
                ('etapa', models.IntegerField(choices=[(1, 'Formalidades (Pre-construcción)'), (2, 'Construcción e instalación de Sistema bebedero'), (3, 'Entrega del sistema bebedero'), (4, 'Mantenimiento')])),
                ('creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor', to=settings.AUTH_USER_MODEL)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escuela_incidencia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
