# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Incidencias',
            new_name='Incidencia',
        ),
        migrations.AlterModelOptions(
            name='incidencia',
            options={'ordering': ['creacion']},
        ),
    ]
