# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-25 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0002_auto_20170731_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='prioridad',
            field=models.IntegerField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')]),
        ),
    ]
