# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-25 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0003_auto_20170825_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='prioridad',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=5),
        ),
    ]
