# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-25 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0004_auto_20170825_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='etapa',
            field=models.CharField(choices=[('Formalidades (Pre-construcción)', 'Formalidades (Pre-construcción)'), ('Pruebas de calidad de agua', 'Pruebas de calidad de agua'), ('Construcción e instalación de Sistema bebedero', 'Construcción e instalación de Sistema bebedero'), ('Entrega del sistema bebedero', 'Entrega del sistema bebedero'), ('Mantenimiento', 'Mantenimiento')], max_length=100),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='status',
            field=models.CharField(choices=[('En espera', 'En espera'), ('En proceso de solución', 'En proceso de solución'), ('Solucionado', 'Solucionado')], default='En espera', max_length=30),
        ),
    ]
