# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-25 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0005_auto_20170825_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='status',
            field=models.CharField(choices=[('En espera', 'En espera'), ('Atendiendo', 'Atendiendo'), ('Solucionado', 'Solucionado')], default='En espera', max_length=30),
        ),
    ]
