# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-26 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0006_auto_20170825_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidencia',
            name='escuela',
        ),
    ]
