# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-26 17:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidencias', '0007_remove_incidencia_escuela'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='escuela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escuela_incidencia', to=settings.AUTH_USER_MODEL),
        ),
    ]
