# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-29 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0008_incidencia_escuela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
    ]
