# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-31 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0009_auto_20170829_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidencia',
            old_name='etapa',
            new_name='fase',
        ),
    ]
