# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-27 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0010_auto_20170831_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='solucion',
            field=models.TextField(blank=True, null=True, verbose_name='Solución'),
        ),
    ]
