# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-27 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0013_auto_20171014_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='prioridad',
            field=models.CharField(choices=[('Ninguna', 'Ninguna (Es una notificación)'), ('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=5),
        ),
    ]
