# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-29 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0014_auto_20171027_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='prioridad',
            field=models.CharField(choices=[('Ninguna', 'Ninguna (Es una notificación)'), ('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=10),
        ),
    ]
