# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-19 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0015_auto_20171028_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='evidencia',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
