# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-19 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0016_incidencia_evidencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='incidencias/%Y/%m/%d/', verbose_name='Evidencia fotográfica'),
        ),
    ]
