# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-19 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0017_auto_20180619_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='evidencia_2',
            field=models.ImageField(blank=True, null=True, upload_to='incidencias/%Y/%m/%d/', verbose_name='Evidencia fotográfica solución'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='incidencias/%Y/%m/%d/', verbose_name='Evidencia fotográfica de incidencia'),
        ),
    ]
