# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-13 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0019_auto_20180619_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='fecha_solucion',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de solucion'),
        ),
    ]
