# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-13 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0020_incidencia_fecha_solucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='creacion',
            field=models.DateTimeField(verbose_name='Fecha de creación'),
        ),
    ]
