# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-13 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0021_auto_20190112_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='fecha_solucion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de solucion'),
        ),
    ]
