# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-07-01 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0100_perfil_expediente_completo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre o número')),
                ('archivo', models.FileField(upload_to='doc/%Y/%m/%d/')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha de subida del Informe de respuesta de a Oficio')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Entidad')),
            ],
        ),
    ]
