# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-07-01 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficio',
            name='fecha',
            field=models.DateField(verbose_name='Fecha de subida'),
        ),
    ]
