# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-07-22 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0002_auto_20190701_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficio',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre o número'),
        ),
    ]
